### ISSUE TITLE
Undefined Symbol: libiconv on Ubuntu 16.04

### ISSUE THREAD

**Issue by VMRuiz** [openai/universe#1]
Hello, I tried to install the universe package as in the installation guide but when I import it I get this error:

```
>>> import universe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "universe/__init__.py", line 21, in <module>
    from universe import error, envs
  File "universe/envs/__init__.py", line 1, in <module>
    import universe.envs.vnc_env
  File "universe/envs/vnc_env.py", line 18, in <module>
    from universe.envs import diagnostics
  File "universe/envs/diagnostics.py", line 2, in <module>
    import fastzbarlight
  File "/home/vruiz/ws/game-ml/.venv/local/lib/python2.7/site-packages/fastzbarlight/__init__.py", line 7, in <module>
    from ._zbarlight import zbar_code_scanner
ImportError: /home/vruiz/ws/game-ml/.venv/local/lib/python2.7/site-packages/fastzbarlight/_zbarlight.so: undefined symbol: libiconv
>>> 
```

I think I have that lib on my system:
```
(.venv) ➜  universe git:(master) ldconfig -p | grep libiconv
	libiconv_hook.so.1 (libc6,x86-64) => /usr/lib/libiconv_hook.so.1
	libiconv_hook.so (libc6,x86-64) => /usr/lib/libiconv_hook.so
	libiconv.so.2 (libc6,x86-64) => /usr/local/lib/libiconv.so.2
	libiconv.so (libc6,x86-64) => /usr/local/lib/libiconv.so
```

Any idea on how to solve this? Thank you.

**Comment by gdb** [comment]
We try to do some detection about whether you have `libiconv`, but I think it got it wrong here. (cf https://github.com/gdb/zbarlight/blob/master/setup.py#L49-L54).

Try doing `pip install fastzbarlight==0.0.14.dev0` — this is a built which hardcodes `libraries = ['iconv']`. If it works, we should use a better dynamic detection.

**Comment by VMRuiz** [comment]
Thanks for the suggestion but I keep getting the same error as before. I include the list of packages on the environment I'm running it to see if that helps: 
```
autobahn (0.17.0)
backports.ssl-match-hostname (3.5.0.1)
constantly (15.1.0)
docker-py (1.10.3)
docker-pycreds (0.2.1)
fastzbarlight (0.0.14.dev0)
go-vncdriver (0.4.17)
gym (0.5.6)
incremental (16.10.1)
ipaddress (1.0.17)
numpy (1.11.2)
Pillow (3.4.2)
pip (9.0.1)
pkg-resources (0.0.0)
pyglet (1.2.4)
PyYAML (3.12)
requests (2.10.0)
setuptools (30.2.0)
six (1.10.0)
Twisted (16.6.0)
txaio (2.5.2)
ujson (1.35)
universe (0.20.2, /home/vruiz/ws/game-ml/universe)
websocket-client (0.39.0)
wheel (0.30.0a0)
zope.interface (4.3.2)
```

**Comment by prakashyadav008** [comment]
I have installed all the necessary packages but i am still getting these error's
/*
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/universe/__init__.py", line 21, in <module>
    from universe import error, envs
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/universe/envs/__init__.py", line 1, in <module>
    import universe.envs.vnc_env
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/universe/envs/vnc_env.py", line 20, in <module>
    from universe.runtimes import registration
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/universe/runtimes/__init__.py", line 6, in <module>
    with open(os.path.join(os.path.dirname(__file__), '../../runtimes.yml')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/prakash/anaconda3/lib/python3.5/site-packages/universe/runtimes/../../runtimes.yml'
*/

**Comment by VMRuiz** [comment]
I also run into the @prakashyadav008 error during one of my installation' attempts, but right now I can't reproduce the steps to get it again.

**Comment by gdb** [comment]
@VMRuiz what's the output of `ld -liconv`? You can view the source for this package here: https://github.com/openai/zbarlight; here's the code which decides whether to pass a `-liconv`: https://github.com/openai/zbarlight/blob/master/setup.py#L49-L54 in the build.

The real fix here is to change the vendored zbar to never build with iconv, since we don't need it. If you're up for some build hacking would love the help :).

**Comment by jeremyschlatter** [comment]
@prakashyadav008 Looks like our release was pushed incorrectly to PyPI. I'll fix it..

**Comment by VMRuiz** [comment]
@gdb Finally I manage to understand what the problem was.

My system locale was in spanish so when the installation executed `ld -liconv` the returned error was `ld: no se puede encontrar -liconv` and because of this it wasn't match as an error by the installation script.

Once I change my local output to english I was able to install it without any other problem.

I would love to help you fix this but I don't know enough to make a general fix for this.

**Comment by jeremyschlatter** [comment]
Made an attempt at removing iconv here: https://github.com/openai/zbarlight/tree/hack-iconv

Not quite there, though. I think I might just make the `ld -liconv` workaround a little more robust.

**Comment by illiatdesdindes** [comment]
on  Ubunutu :

```
pip install numpy
sudo apt-get install golang libjpeg-turbo8-dev make

LANG=en_US.utf8
LANGUAGE=en_US

git clone https://github.com/openai/universe.git
cd universe
pip install -e .

```

**Comment by prakashyadav008** [comment]
@jeremyschlatter still showing the same errors
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/universe/__init__.py", line 21, in <module>
    from universe import error, envs
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/universe/envs/__init__.py", line 1, in <module>
    import universe.envs.vnc_env
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/universe/envs/vnc_env.py", line 20, in <module>
    from universe.runtimes import registration
  File "/home/prakash/anaconda3/lib/python3.5/site-packages/universe/runtimes/__init__.py", line 6, in <module>
    with open(os.path.join(os.path.dirname(__file__), '../../runtimes.yml')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/prakash/anaconda3/lib/python3.5/site-packages/universe/runtimes/../../runtimes.yml'`

**Comment by jeremyschlatter** [comment]
@prakashyadav008 Just pushed a fix for the runtimes.yml issue.

@VMRuiz I just pushed a new version of fastzbarlight that should install correctly regardless of locale. Thanks for tracking down the problem!
