### ISSUE TITLE
Unable to import universe, No module named benchmarks

### ISSUE THREAD

**Issue by arsenious** [openai/universe#103]
### Expected behavior
import universe should happen smoothly

### Actual behavior

>>> import gym
>>> import universe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/Tutorials/TFTuts/universe/universe/__init__.py", line 20, in <module>
    import universe.scoreboard
  File "/home/username/Tutorials/TFTuts/universe/universe/scoreboard/__init__.py", line 4, in <module>
    from gym.benchmarks import scoring
ImportError: No module named benchmarks

### Versions
Please include the result of running
```
$ uname -a ; python --version; pip show universe gym tensorflow numpy go-vncdriver Pillow
```
(Actual names replaced with ComputerName and username )

Linux ComputerName 4.4.0-53-generic #74~14.04.1-Ubuntu SMP Fri Dec 2 03:43:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.11 :: Anaconda custom (64-bit)
---
Name: universe
Version: 0.21.1
Location: /home/username/Tutorials/TFTuts/universe
Requires: autobahn, docker-py, docker-pycreds, fastzbarlight, go-vncdriver, gym, Pillow, PyYAML, six, twisted, ujson
---
Name: gym
Version: 0.7.0
Location: /home/username/Tutorials/TFTuts/gym
Requires: numpy, requests, six, pyglet
---
Name: numpy
Version: 1.11.1
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
---
Name: go-vncdriver
Version: 0.4.19
Location: /usr/local/lib/python2.7/dist-packages
Requires: numpy
---
Name: Pillow
Version: 4.0.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: olefile

__________________________________

All of this is inside a Python 2.7 Anaconda Env.

Is there is a specific directory hierarchy that must be followed wrt. gym and universe folders? Right now both are installed side-by-side in the same overall directory.

Thanks

**Comment by tlbtlbtlb** [comment]
Most likely, you have another file called gym.py that is being found first. 

You can track this down by:
```
$ python
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym
gym
>>> gym.__file__
'/Users/tlb/openai/gym/gym/__init__.py'
```

For you it should be `/home/username/Tutorials/TFTuts/gym/gym/__init__.py`.

If that gives you something other than where the entire gym module is, that's the problem.

**Comment by arsenious** [comment]
Thank you very much for your reply!

This is the output /home/username/anaconda2/envs/tensorflow/lib/python2.7/site-packages/gym/__init__.pyc

which is clearly not the same.

I think this has happened because I first did pip install from inside the env and then later after a while used the setup.py script to install gym. How should I proceed?
Should I directly delete the folder at the incorrect location?

I'm relatively new to all this, so thanks for bearing with my issues.

**Comment by arsenious** [comment]
I deleted the folder at the wrong location. But from within the conda env, it was still not importing. So I edited my bashrc and added the correct path to PYTHONPATH to both gym and universe. Then autobahn wasn't importing so I git cloned it and installed it and added its path into PYTHONPATH as well. But now twisted isnt getting imported

*******************************
>>> import gym
>>> import universe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/Tutorials/TFTuts/universe/universe/__init__.py", line 22, in <module>
    from universe import error, envs
  File "/home/username/Tutorials/TFTuts/universe/universe/envs/__init__.py", line 1, in <module>
    import universe.envs.vnc_env
  File "/home/username/Tutorials/TFTuts/universe/universe/envs/vnc_env.py", line 8, in <module>
    from universe import error, pyprofile, rewarder, spaces, twisty, vectorized, vncdriver
  File "/home/username/Tutorials/TFTuts/universe/universe/rewarder/__init__.py", line 1, in <module>
    from universe.rewarder.rewarder_session import RewarderSession
  File "/home/username/Tutorials/TFTuts/universe/universe/rewarder/rewarder_session.py", line 1, in <module>
    from autobahn.twisted import websocket
  File "/home/username/Tutorials/TFTuts/autobahn-python/autobahn/twisted/__init__.py", line 33, in <module>
    import twisted
ImportError: No module named twisted
***********************************

But when I do pip install twisted 
(tensorflow) username ~ $ pip install twisted
Requirement already satisfied (use --upgrade to upgrade): twisted in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): zope.interface>=3.6.0 in /usr/lib/python2.7/dist-packages (from twisted)
Requirement already satisfied (use --upgrade to upgrade): constantly>=15.1 in /usr/local/lib/python2.7/dist-packages (from twisted)
Requirement already satisfied (use --upgrade to upgrade): incremental>=16.10.1 in /usr/local/lib/python2.7/dist-packages (from twisted)
**********************************

So I added that as well to the PYTHONPATH. So finally in bashrc, 
export PYTHONPATH=/home/username/Tutorials/TFTuts/gym:/home/username/Tutorials/TFTuts/universe:/home/username/Tutorials/TFTuts/autobahn-python:/usr/local/lib/python2.7/dist-packages/autobahn/twisted


But still I'm unable to import twisted.

I think I'm doing stuff incorrectly and the mess is just piling up. Should I delete all these folders and start again ? Or should I start a whole new environment? I've spent a lot of time already getting tensorflow, keras, gym, golang etc. to work in this Python 2.7 env. I had a lot of issues with packages getting installed in the usr/ folder instead of the tensorflow env folder inside anaconda.


Thanks for your time and help. Really appreciate it

**Comment by tlbtlbtlb** [comment]
Putting directories in `PYTHONPATH` doesn't work for complex packages like Autobahn. It needs to be installed with `pip`. Anaconda works best with an empty `PYTHONPATH`.

It really should work from a clean Anaconda environment, by just running (in the `universe` directory) `pip install -e .`. That'll install the dependencies like Autobahn.

**Comment by arsenious** [comment]
I think I got it to work in a fresh 3.5 conda env. I followed the instructions here:https://alliseesolutions.wordpress.com/2016/12/08/openai-universe-installation-guide-ubuntu-16-04/

But I couldn't get his example to work but the DuskDrive example in the readme of this repo seems to work. At least the VNC starts and you can see the Play button. But nothing happens after that. I guess the AI doesnt know how to click the Play button?

![image](https://cloud.githubusercontent.com/assets/24788213/21753676/02b18b06-d5c0-11e6-986c-72b965323cb1.png)

**Comment by tlbtlbtlb** [comment]
The environment itself should click the play button (it has a built in logic to get the game started). I'm not sure what could cause it to fail on your system. Could you include the complete logs from the session?

**Comment by arsenious** [comment]
I noticed that the Mouse keeps oscillating between (429,539) , (430, 539) and (25,100)

Logs attached
[DuskDrive_log.txt](https://github.com/openai/universe/files/692735/DuskDrive_log.txt)

Thanks

**Comment by Henil231** [comment]
I am Using jupyter with Anaconda,But whenever I'm trying to import universe it is giving me this error.What am I doing wrong?
Please help me out.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-a285d58c8ea7> in <module>()
      1 import gym
----> 2 import universe
      3 import random

ModuleNotFoundError: No module named 'universe'

**Comment by tlbtlbtlb** [comment]
You must not have installed universe. See instructions at https://github.com/openai/universe#install-universe. If that doesn't work, please paste a complete transcript.

**Comment by arsenious** [comment]
Yes either you haven't installed Universe or you installed it outside the Anaconda Environment (if you are are using one).
