### ISSUE TITLE
Why doesn’t OpenAI use NX server instead (e.g. Google’s NeatX) of VNC? 

### ISSUE THREAD

**Issue by shyamalschandra** [openai/universe#118]
Link: 
1. NeatX (Google): https://code.google.com/archive/p/neatx/ (Python)
2. X2Go: http://wiki.x2go.org/doku.php/about:start (Python)

Look at this article:
http://www.keycruncher.com/blog/2008/07/07/vnc-vs-nomachine-nx-nomachine-wins-hands-down/1

Have you weighed the pros and cons of using VNC versus NX and other open-source remote desktop software protocols?

**Comment by tlbtlbtlb** [comment]
We haven't seriously considered them. For games, where most of the pixels in the game window change every cycle, they don't have obvious advantages. The current VNC implementation can handle multiple 60 FPS streams per core. But if you want to make a case for a different remote desktop protocol, a working implementation and performance comparison would be interesting to see.

**Comment by tlbtlbtlb** [comment]
Closing, but reopen if there's a good case for changing
