### ISSUE TITLE
Is it possible to package GTAV and other Win7/10 games inside a Dockers container? 

### ISSUE THREAD

**Issue by shyamalschandra** [openai/universe#119]
Similar to the Flash and other games like `flashgames.DuskDrive-v0` that run and communicate with a VNC server using Docker running on the local machine, isn't it possible to do the same with Windows 7/8/10 Docker container?  This might be useful for many reasons.  Any thoughts?

Link:
https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

**Comment by tlbtlbtlb** [comment]
Can you be more specific about how you think Universe could use this?

**Comment by shyamalschandra** [comment]
Has anyone yet added Madden NFL, NBA 2K, NHL, FIFA, and NHL series on universe catalog of games?

If not, I would like to initiate it. I am just checking to see if someone has already done it with the latest PC versions of sports simulation games.

**Comment by maxtom** [comment]
@shyamalschandra 
Hi, is there any new progress on this issue, I also want Package GTA V on my desktop, and run the client on the local server.
