### ISSUE TITLE
How could I build an custom env (without vnc)

### ISSUE THREAD

**Issue by MTRNord** [openai/universe#12]
I got an arduino powered robot here and I would like to be able to add an custom env with that I want connect via wlan (or lets say for simplicity per gpio)  to let universe control it. Which things would I have to modify or where should I start to build that? Is there some file which I could use as base that does let me add some kind of env for my robot? Especialy I mean which file I have to modify to get signals from universe to the robot and the other way around.

**Comment by gdb** [comment]
Here's a good starting point: https://github.com/openai/universe/blob/master/universe/envs/dummy_vnc_env.py. You need to accept actions and return observation/reward/done/info. Your action format should be a list of keyboard/mouse commands, and your observation should be a dictionary with a numpy "vision" buffer.

**Comment by gdb** [comment]
(If these actions/observations don't make sense for your robot, you can still make a standard Gym environment for it: https://github.com/openai/gym/tree/master/gym/envs#how-to-create-new-environments-for-gym.)

**Comment by MTRNord** [comment]
Thanks for awnser :) I will take a look at it.
