### ISSUE TITLE
Documentation for Universe 

### ISSUE THREAD

**Issue by shyamalschandra** [openai/universe#120]
Do you think it would be helpful if I start a readthedoc for universe because I am scrolling through the source and besides the initial program written on the universe.openai.com page, there isn't any example code?  I would like to show examples of deep neural networks in a control-perception loop with a Universe game.  Any feedback?  I was thinking of using readthedocs or some github pages for universe.

**Comment by tlbtlbtlb** [comment]
http://github.com/openai/universe-starter-agent is a complete agent example.
If you're making a working agent, just publish it as a github repository.
