### ISSUE TITLE
Can't run environment for duskdrive

### ISSUE THREAD

**Issue by jamielaw** [openai/universe#124]
(First, please check https://github.com/openai/universe/wiki/Solutions-to-common-problems for solutions to many common problems)

### Expected behavior
I have run it before and it successfully loaded the environment showing the agent playing DuskDrive. I closed it and exited, but when I tried to re-run it, I get this traceback message below.
### Actual behavior
 Making new env: flashgames.DuskDrive-v0
Traceback (most recent call last):
  File "duskdrive.py", line 5, in <module>
    observation_n = env.reset()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gym/core.py", line 123, in reset
    observation = self._reset()
  File "/Github/universe/universe/wrappers/timer.py", line 15, in _reset
    return self.env.reset()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gym/core.py", line 123, in reset
    observation = self._reset()
  File "/Github/universe/universe/wrappers/render.py", line 25, in _reset
    observation_n = self.env.reset()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gym/core.py", line 123, in reset
    observation = self._reset()
  File "/Github/universe/universe/wrappers/throttle.py", line 42, in _reset
    observation = self.env.reset()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gym/core.py", line 123, in reset
    observation = self._reset()
  File "/Github/universe/universe/envs/vnc_env.py", line 331, in _reset
    self._handle_connect()
  File "/Github/universe/universe/envs/vnc_env.py", line 498, in _handle_connect
    for remote in self.remote_manager.pop(n=n):
AttributeError: 'VNCEnv' object has no attribute 'remote_manager'
### Versions
Please include the result of running
```
$ uname -a ; 

python --version;
python --version
Python 2.7.10
python3 --version
Python 3.5.1

pip show universe gym tensorflow numpy go-vncdriver Pillow
Name: universe
Version: 0.21.2
Summary: Universe: a software platform for measuring and training an AI's general intelligence across the world's supply of games, websites and other applications.
Home-page: https://github.com/openai/universe
Author: OpenAI
Author-email: universe@openai.com
License: UNKNOWN
Location: /Users/jamie/Github/universe
Requires: autobahn, docker-py, docker-pycreds, fastzbarlight, go-vncdriver, gym, Pillow, PyYAML, six, twisted, ujson
---
Name: gym
Version: 0.7.2
Summary: The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.
Home-page: https://github.com/openai/gym
Author: OpenAI
Author-email: gym@openai.com
License: UNKNOWN
Location: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requires: pyglet, numpy, six, requests
---
Name: numpy
Version: 1.12.0
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@scipy.org
License: BSD
Location: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requires: 
---
Name: go-vncdriver
Version: 0.4.19
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requires: numpy
---
Name: Pillow
Version: 4.0.0
Summary: Python Imaging Library (Fork)
Home-page: http://python-pillow.org
Author: Alex Clark (Fork Author)
Author-email: aclark@aclark.net
License: Standard PIL License
Location: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requires: olefile
```

**Comment by tlbtlbtlb** [comment]
You need to configure the environment before calling using it and calling reset. `env.configure(remotes=1)`

**Comment by jamielaw** [comment]
Weird, that line was included when I ran the code. Regardless, it works now and thanks for the help!
