### ISSUE TITLE
AttributeError:'VectorizeFilter' object has no attribute 'filter_n'

### ISSUE THREAD

**Issue by johnholl** [openai/universe#125]
(First, please check https://github.com/openai/universe/wiki/Solutions-to-common-problems for solutions to many common problems)

### Actual behavior
When I attempt to run train.py the two agent threads both produce the titled attribute error. 

Looking in the /universe/universe/vectorized/vectorize_filter.py file, I see filter_n is defined in the _configure function. If I place self._configure() in __init__ the problem goes away. This is the first time I've looked at the code though so I don't know if this is the correct solution.

### Versions
Linux Wintermute 3.13.0-86-generic #131-Ubuntu SMP Thu May 12 23:33:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Python 2.7.6
universe  0.20.2
tensorflow 0.12.1
numpy 1.11.1
go-vncdriver 0.4.19
Pillow 2.3.0

**Comment by tlbtlbtlb** [comment]
Updating universe will solve this problem. ie, `pip install --upgrade universe`
