### ISSUE TITLE
Why was GTA V removed?

### ISSUE THREAD

**Issue by wang3303** [openai/universe#126]
(First, please check https://github.com/openai/universe/wiki/Solutions-to-common-problems for solutions to many common problems)

### Expected behavior
Are you going to release GTA V later or not? This game is really great and I hope it can be released again.
### Actual behavior
I checked the deepdrive.io and GTA+universe today but almost all the resources were removed.
### Versions
Please include the result of running
```
$ uname -a ; python --version; pip show universe gym tensorflow numpy go-vncdriver Pillow
```

**Comment by kyelok** [comment]
Do we have answers to this?

**Comment by remzr7** [comment]
Do we actually have answers to this?

**Comment by tomchen1000** [comment]
Nope. It seems that OpenAI is not so open on this.

Tom

**Comment by brummell** [comment]
so maybe _Open_AI is a bit of a misnomer?

**Comment by efun100** [comment]
http://deepdrive.io/  
Unfortunately, however, we are restricted from providing resources using GTAV for legal reasons.
