### ISSUE TITLE
How to run pc games?

### ISSUE THREAD

**Issue by aaroncheung123** [openai/universe#131]
I am able to run most of the environments in universe using this code (code from the documentation)

`import gym
import universe  # register the universe environments

env = gym.make('**flashgames.DuskDrive-v0**')
env.configure(remotes=1)  # automatically creates a local docker container
observation_n = env.reset()`

I just change whatever is in gym.make.  However, when I change it to an environment to a pc game the error I get is "error.UnregisteredEnv('No registered env with id".  Does anyone know how to fix this?

**Comment by tlbtlbtlb** [comment]
Which PC game do you mean? There are only a couple available in the current release: `world.WorldOfGoo-v0` and `starcraft.TerranAstralBalance-v0`.

**Comment by aaroncheung123** [comment]
Ohhhh now I see that it says "coming soon".  How did you know that world of goo and start craft were available,  Those also say "coming soon".

**Comment by tlbtlbtlb** [comment]
Sorry, they're not available yet either, I was looking at the wrong list.
