### ISSUE TITLE
Running Headless

### ISSUE THREAD

**Issue by aaroncheung123** [openai/universe#132]
When I run the code from the documentation 

`import gym
import universe  # register the universe environments

env = gym.make('flashgames.DuskDrive-v0')
env.configure(remotes=1)  # automatically creates a local docker container
observation_n = env.reset()

while True:
  action_n = [[('KeyEvent', 'ArrowUp', True)] for ob in observation_n]  # your agent here
  observation_n, reward_n, done_n, info = env.step(action_n)
  env.render()`

Theres always a window that pops up and shows the game being played by the ai.  How can I make it run headless?

**Comment by tlbtlbtlb** [comment]
Just take out the call to `env.render()`
