### ISSUE TITLE
Running gym environments (Doom, Minecraft, and etc)

### ISSUE THREAD

**Issue by aaroncheung123** [openai/universe#133]
When I run this code
`import gym
import universe  # register the universe environments

env = gym.make('MinecraftDefaultWorld1-v0')
env.configure(remotes=1)  # automatically creates a local docker container
observation_n = env.reset()

while True:
  action_n = [[('KeyEvent', 'ArrowUp', True)] for ob in observation_n]  # your agent here
  observation_n, reward_n, done_n, info = env.step(action_n)
  env.render()`

The error I get is gym.error.UnregisteredEnv("no registered env with id:".  This happens with every gym environment I try when I change the gym.make.  How do you fix this?

**Comment by tlbtlbtlb** [comment]
The Minecraft environments aren't released yet either.

Good ones to start with are at https://universe.openai.com/envs#flash_games

**Comment by aaroncheung123** [comment]
On this website https://github.com/tambetm/gym-minecraft it shows you how to run and install Minecraft.  I'm assuming your telling me that I can't run these environments in universe yet but I can in gym.  Is that right?  Also how do I know when they are released?  For PC games I understand that because it says coming soon.  As for Minecraft and Doom it says experimental.

**Comment by tlbtlbtlb** [comment]
Yes, they work in gym when you load the add-on packages, either
https://github.com/ppaquette/gym-doom or https://github.com/tambetm/gym-minecraft.
