### ISSUE TITLE
pip3 check returns: universe 0.21.2 has requirement docker-py==1.10.3, but you have docker-py 1.10.6.

### ISSUE THREAD

**Issue by jrking123** [openai/universe#138]
`pip3 check` returns: 
`universe 0.21.2 has requirement docker-py==1.10.3, but you have docker-py 1.10.6.`

Thanks, John

Darwin frodo.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64 i386 MacBookPro11,5 Darwin

Python 3.6.0   (Homebrew installed)

Name: universe
Version: 0.21.2
Summary: Universe: a software platform for measuring and training an AI's general intelligence across the world's supply of games, websites and other applications.
Home-page: https://github.com/openai/universe
Author: OpenAI
Author-email: universe@openai.com
License: UNKNOWN
Location: /usr/local/lib/python3.6/site-packages
Requires: gym, fastzbarlight, docker-pycreds, twisted, docker-py, autobahn, go-vncdriver, ujson, Pillow, PyYAML, six

Name: gym
Version: 0.7.3
Summary: The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.
Home-page: https://github.com/openai/gym
Author: OpenAI
Author-email: gym@openai.com
License: UNKNOWN
Location: /usr/local/lib/python3.6/site-packages
Requires: numpy, pyglet, six, requests

Name: tensorflow
Version: 1.0.0a0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.6/site-packages
Requires: wheel, protobuf, numpy, six

Name: numpy
Version: 1.12.0
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@scipy.org
License: BSD
Location: /usr/local/lib/python3.6/site-packages
Requires:

Name: go-vncdriver
Version: 0.4.19
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /usr/local/lib/python3.6/site-packages
Requires: numpy

Name: Pillow
Version: 4.0.0
Summary: Python Imaging Library (Fork)
Home-page: http://python-pillow.org
Author: Alex Clark (Fork Author)
Author-email: aclark@aclark.net
License: Standard PIL License
Location: /usr/local/lib/python3.6/site-packages
Requires: olefile

Name: docker-py
Version: 1.10.6
Summary: Python client for Docker.
Home-page: https://github.com/docker/docker-py/
Author: Joffrey F
Author-email: joffrey@docker.com
License: UNKNOWN
Location: /usr/local/lib/python3.6/site-packages
Requires: six, docker-pycreds, requests, websocket-client

**Comment by tlbtlbtlb** [comment]
That is a requirement. Unfortunately, docker-py 1.10.6 is incompatible with 1.10.3
