### ISSUE TITLE
import universe gives Symbol not found: _iconv

### ISSUE THREAD

**Issue by bichengcao** [openai/universe#139]
Running the Dustdrive code and have the following error.

```
$ python universe_duskdrive.py
Traceback (most recent call last):
  File "universe_duskdrive.py", line 2, in <module>
    import universe  # register the universe environments
  File "/Users/bichengcao/Projects/universe/universe/__init__.py", line 22, in <module>
    from universe import error, envs
  File "/Users/bichengcao/Projects/universe/universe/envs/__init__.py", line 1, in <module>
    import universe.envs.vnc_env
  File "/Users/bichengcao/Projects/universe/universe/envs/vnc_env.py", line 10, in <module>
    from universe.envs import diagnostics
  File "/Users/bichengcao/Projects/universe/universe/envs/diagnostics.py", line 2, in <module>
    import fastzbarlight
  File "/Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages/fastzbarlight/__init__.py", line 7, in <module>
    from ._zbarlight import zbar_code_scanner
ImportError: dlopen(/Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages/fastzbarlight/_zbarlight.cpython-35m-darwin.so, 2): Symbol not found: _iconv
  Referenced from: /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages/fastzbarlight/_zbarlight.cpython-35m-darwin.so
  Expected in: flat namespace
 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages/fastzbarlight/_zbarlight.cpython-35m-darwin.so
```

### Versions
anaconda python 3.5 env.
universe installed successfully, and fastzbarlight-0.0.14 was built successfully.

```
$ sudo pip install -e .
The directory '/Users/bichengcao/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/bichengcao/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///Users/bichengcao/Projects/universe
Requirement already satisfied: autobahn>=0.16.0 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from universe==0.21.2)
Requirement already satisfied: docker-py==1.10.3 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from universe==0.21.2)
Requirement already satisfied: docker-pycreds==0.2.1 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from universe==0.21.2)
Collecting fastzbarlight>=0.0.13 (from universe==0.21.2)
  Downloading fastzbarlight-0.0.14.tar.gz (728kB)
    100% |████████████████████████████████| 737kB 723kB/s
Requirement already satisfied: go-vncdriver>=0.4.8 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from universe==0.21.2)
Requirement already satisfied: gym>=0.7.0 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from universe==0.21.2)
Requirement already satisfied: Pillow>=3.3.0 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from universe==0.21.2)
Requirement already satisfied: PyYAML>=3.12 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from universe==0.21.2)
Requirement already satisfied: six>=1.10.0 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from universe==0.21.2)
Requirement already satisfied: twisted>=16.5.0 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from universe==0.21.2)
Requirement already satisfied: ujson>=1.35 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from universe==0.21.2)
Requirement already satisfied: txaio>=2.5.2 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from autobahn>=0.16.0->universe==0.21.2)
Requirement already satisfied: requests<2.11,>=2.5.2 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from docker-py==1.10.3->universe==0.21.2)
Requirement already satisfied: websocket-client>=0.32.0 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from docker-py==1.10.3->universe==0.21.2)
Requirement already satisfied: numpy in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from go-vncdriver>=0.4.8->universe==0.21.2)
Requirement already satisfied: pyglet>=1.2.0 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from gym>=0.7.0->universe==0.21.2)
Requirement already satisfied: olefile in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from Pillow>=3.3.0->universe==0.21.2)
Requirement already satisfied: zope.interface>=4.0.2 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from twisted>=16.5.0->universe==0.21.2)
Requirement already satisfied: constantly>=15.1 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from twisted>=16.5.0->universe==0.21.2)
Requirement already satisfied: incremental>=16.10.1 in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages (from twisted>=16.5.0->universe==0.21.2)
Requirement already satisfied: setuptools in /Users/bichengcao/anaconda/envs/rl-3.5/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg (from zope.interface>=4.0.2->twisted>=16.5.0->universe==0.21.2)
Installing collected packages: fastzbarlight, universe
  Running setup.py install for fastzbarlight ... done
  Running setup.py develop for universe
Successfully installed fastzbarlight-0.0.14 universe
```

**Comment by tlbtlbtlb** [comment]
Can you report the output of
```
uname -a
```
and
```
ld -liconv
```

**Comment by bichengcao** [comment]
```
(rl-3.5) myhost:rl bichengcao$ uname -a
Darwin myhost.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
(rl-3.5) myhost:rl bichengcao$ ld -liconv
ld: warning: -arch not specified
ld: warning: -macosx_version_min not specified, assuming 10.10
Undefined symbols for architecture x86_64:
  "start", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for inferred architecture x86_64
```

**Comment by tlbtlbtlb** [comment]
@jeremyschlatter It's not clear why it's building without `-liconv`. Do you have a macOS Sierra machine to test on?

**Comment by Saxamos** [comment]
Same issue here with the same configuration

**Comment by siddheshmhatre** [comment]
Facing the same issue with macOS sierra and anaconda python 3.6

**Comment by tonyabracadabra** [comment]
Have you figured out how to fix this? I met the same problem here.

**Comment by tonyabracadabra** [comment]
I finally run "pip uninstall fastzbarlight" to uninstall the fastzbarlight package and reinstall its alternative package with "pip install zbarlight", then manually change the "import fastzbarlight" to "import zbarlight" and the functions associated with that package under the file "./universe/universe/envs/diagnostics.py" and it works.

**Comment by Saxamos** [comment]
Didn't work for me, still the same _iconv error.

**Comment by tlbtlbtlb** [comment]
If anyone with MacOS Sierra can track this down and fix it, I'd really appreciate it.

**Comment by maheshwarLigade** [comment]
This is the exception is getting while I am try to 
import universe
 Reason: Incompatible library version: _zbarlight.cpython-35m-darwin.so requires version 8.0.0 or later, but libiconv.2.dylib provides version 7.0.0

**Comment by schettino** [comment]
Same here (macOS sierra and anaconda python 3.6)

**Comment by maheshwarLigade** [comment]
same here i have macOS yosemite and python3.6

**Comment by wmayer7** [comment]
If you have Macports installed, the issue may be that fastzbarlight is being linked to Macport's libiconv in /opt/local/lib and not to Apple's version in /usr/lib. The former provides symbols _libiconv, _libiconv_open, _libiconv_close, whereas Apple's libiconv provides _iconv, _iconv_open, _iconv_close. If for some reason the build process gets confused between the two, you may end up with an object file that expects _iconv while being linked to a library that provides _libiconv.

I could resolve this by forcing fastzbarlight to compile and link against Macport's libiconv. 
This requires patching setup.py to inject appropriate arguments into the build process. 

Here is what I did:

    pip download fastzbarlight
    tar zxf fastzbarlight-0.0.14.tar.gz
    cd fastzbarlight-0.0.14

Now edit setup.py and change line 29 as follows:
Add CPPFLAGS and LDFLAGS arguments. 
This will force the build tools to use the Macports version of libiconv.
The resulting line reads as follows:

    cmd = ['./configure', '--disable-dependency-tracking', '--without-python', '--without-qt', '--disable-video', '--without-gtk', '--without-imagemagick', '--with-x=no', 'CFLAGS=-Wall -Wno-parentheses -D_FORTIFY_SOURCE=1 -O3 -fPIC','CPPFLAGS=-I/opt/local/include','LDFLAGS=-L/opt/local/lib -liconv' ]

Then build and install:

    pip install .

**Comment by wmayer7** [comment]
I could successfully build and load fastzbarlight using Anaconda Python 3.6 on MacOS Sierra 10.12.3:

First, uninstall the broken package:

    pip uninstall fastzbarlight
    
Then, download and extract the sources:

    pip download fastzbarlight
    tar zxf fastzbarlight-0.0.14.tar.gz
    cd fastzbarlight-0.0.14

Now edit setup.py and change line 29 as follows: 
(replace "/ANACONDADIR" with the full path to the 'anaconda' install directory, for example /Users/monty/anaconda)

    cmd = ['./configure', '--disable-dependency-tracking', '--without-python', '--without-qt', '--disable-video', '--without-gtk', '--without-imagemagick', '--with-x=no', 'CFLAGS=-Wall -Wno-parentheses -D_FORTIFY_SOURCE=0 -O3 -fPIC -I/ANACONDADIR/include  -Wl,-rpath,/ANACONDADIR/lib -L/ANACONDADIR/lib']


Then build and install:

    pip install --no-cache-dir .



A conjecture: The linking issues may be due to the introduction of Apple's SIP, which renders selected environment variables related to the linker (DY_LD_LIBRARY_PATH) ineffective. This may break the build process of the zbar library, which ends up being linked incorrectly. The above patch works around this issue by supplying the relevant include and library paths directly to the build toolchain.

**Comment by Saxamos** [comment]
Great, thank you. It worked well for me :)
I can now import universe.

**Comment by gnarlymedia** [comment]
Thanks wmayer7, your solution of 22 days ago above worked for me as well on Anaconda Python 2.7.13 on MacOS Sierra 10.12.4, I was successfully able to import universe after this :-D

**Comment by nandakumardevadas** [comment]
Great @wmayer7

**Comment by maheshwarLigade** [comment]
I am till facing the same issue above solution not work for me.

**Comment by clm79207** [comment]
Great @wmayer7 
@maheshwarLigade  
Initially did not work. Try @wmayer7 instructions again and if you have anaconda 3 installed, your directory would be similar to "/Users/monty/anaconda3"

**Comment by MarcGreve** [comment]
@wmayer7 

Which setup.py should I edit? Simply searching for that files gets me this:

<img width="276" alt="screen shot 2017-05-13 at 20 57 45" src="https://cloud.githubusercontent.com/assets/27137714/26028343/dd2b1336-381e-11e7-9ef5-2a8db81f8853.png">

**Comment by maheshwarLigade** [comment]
You will find this setup.py inside your fastzbarlight-0.0.14.tar.gz, after extracting this zip you need to edit file fastzbarlight-0.0.14/setup.py I think as per my understanding you need to amend line no 29.

**Comment by MarcGreve** [comment]
@maheshwarLigade 

Thank you, sir. This worked. Also thanks to @wmayer7 for figuring it out.

Now we're on to this problem when running the sample code from OpenAI:

[2017-05-14 16:31:45,094] Making new env: flashgames.DuskDrive-v0
[2017-05-14 16:31:45,111] Writing logs to file: /tmp/universe-83886.log
[2017-05-14 16:31:45,166] Ports used: []
[2017-05-14 16:31:45,167] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.28. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.28
[2017-05-14 16:31:45,177] Image quay.io/openai/universe.flashgames:0.20.28 not present locally; pulling
0.20.28: Pulling from openai/universe.flashgames

And it stays there forever.

**Comment by grahamseamans** [comment]
I'm confused about what to put where in line 29. can someone lay it out explicitly?
ty

**Comment by maheshwarLigade** [comment]
Below is the line no 29 replace anaconda dir with your directory path.
@wmayer7 explained very well kindly follow the steps which are mentioned by him.

cmd = ['./configure', '--disable-dependency-tracking', '--without-python', '--without-qt', '--disable-video', '--without-gtk', '--without-imagemagick', '--with-x=no', 'CFLAGS=-Wall -Wno-parentheses -D_FORTIFY_SOURCE=0 -O3 -fPIC -I/ANACONDADIR/include  -Wl,-rpath,/ANACONDADIR/lib -L/ANACONDADIR/lib']

**Comment by grahamseamans** [comment]
Thank you! I was missing a bunch of those arguments

**Comment by PiyushGupta007** [comment]
@wmayer7  Thank you, Sir. That really works, can import Universe.

**Comment by wenjunsun** [comment]
Thank you so much!!!@wmayer7 perfectly solve my problem! Now I can import universe!
