### ISSUE TITLE
Source for openai/universe.flashgames

### ISSUE THREAD

**Issue by shreyu86** [openai/universe#14]
This is more of a request than an issue. Where can the source for openai/universe.flashgames image be found? Any plans for making the Dockerfile public?

**Comment by gdb** [comment]
Yep, we'll be releasing it in upcoming weeks, along with tools to integrate
new environments. Sign up for early access here:
https://docs.google.com/a/openai.com/forms/d/e/1FAIpQLScAiW-kIS0mz6hdzzFZJJFlXlicDvQs1TX9XMEkipNwjV5VlA/viewform
.


- gdb

**Comment by shreyu86** [comment]
@gdb Thanks a lot for the swift reply!
