### ISSUE TITLE
iptables permission denied

### ISSUE THREAD

**Issue by andrew-lucker** [openai/universe#140]
### Expected behavior
flashgames docker starts and game starts

### Actual behavior
initializing container fails with permission error
relevant container is quay.io/openai/universe.flashgames:0.20.25

iptables v1.6.0: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
Traceback (most recent call last):
  File "/app/universe-envs/flashgames/init", line 268, in <module>
    sys.exit(main())
  File "/app/universe-envs/flashgames/init", line 182, in main
    subprocess.check_call(['iptables', '-F'])
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['iptables', '-F']' returned non-zero exit status 3

### Versions
Please include the result of running ...
N/A, this is my Rust driver: https://github.com/andrew-lucker/rust-openai
Running latest docker on Mac OSX

**Comment by andrew-lucker** [comment]
FYI, the docker is started without extra flags such as in
https://github.com/openai/universe/blob/master/universe/runtimes/registration.py#L68

**Comment by andrew-lucker** [comment]
reproducible from command line with

docker run quay.io/openai/universe.flashgames:0.20.25

**Comment by tlbtlbtlb** [comment]
The extra flags are necessary: `--ipc host --cap-add SYS_ADMIN --privileged`

**Comment by andrew-lucker** [comment]
OK, that worked. Thank you.
