### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by iHateInventNames** [openai/universe#143]
$ pip install universe

### Expected behavior
success

### Actual behavior
$ pip install universe
Collecting universe
  Downloading universe-0.21.2.tar.gz (133kB)
    100% |████████████████████████████████| 143kB 926kB/s 
Collecting autobahn>=0.16.0 (from universe)
  Downloading autobahn-0.17.1-py2.py3-none-any.whl (256kB)
    100% |████████████████████████████████| 266kB 1.1MB/s 
Collecting docker-py==1.10.3 (from universe)
  Downloading docker_py-1.10.3-py2.py3-none-any.whl (48kB)
    100% |████████████████████████████████| 51kB 2.0MB/s 
Collecting docker-pycreds==0.2.1 (from universe)
  Downloading docker_pycreds-0.2.1-py2.py3-none-any.whl
Collecting fastzbarlight>=0.0.13 (from universe)
  Downloading fastzbarlight-0.0.14.tar.gz (728kB)
    100% |████████████████████████████████| 737kB 502kB/s 
Collecting go-vncdriver>=0.4.8 (from universe)
  Downloading go_vncdriver-0.4.19.tar.gz (638kB)
    100% |████████████████████████████████| 645kB 952kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/z8/368byt_523x0jgsczkk2_gl80000gn/T/pip-build-FUTZoS/go-vncdriver/setup.py", line 8, in <module>
        import build
      File "/private/var/folders/z8/368byt_523x0jgsczkk2_gl80000gn/T/pip-build-FUTZoS/go-vncdriver/build.py", line 8, in <module>
        import numpy
    ImportError: No module named numpy
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/z8/368byt_523x0jgsczkk2_gl80000gn/T/pip-build-FUTZoS/go-vncdriver/

### Versions
Please include the result of running
```
$ uname -a ; python --version; pip show universe gym tensorflow numpy go-vncdriver Pillow
```
$ uname -a ; python --version; pip show universe gym tensorflow numpy go-vncdriver Pillow
Darwin MacBook-Sergej.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
Python 2.7.12

**Comment by tlbtlbtlb** [comment]
```
ImportError: No module named numpy
```

You haven't installed numpy. Make sure to do all the steps for OSX under https://github.com/openai/universe#installation

**Comment by iHateInventNames** [comment]
https://packaging.python.org/distributing/#install-requires
