### ISSUE TITLE
to get started first install universe

### ISSUE THREAD

**Issue by iHateInventNames** [openai/universe#144]
Executing initial steps "to get started first install universe" in readme

### Expected behavior
installation should be successfull

### Actual behavior
name@name-System-Product-Name:~/source$ git clone https://github.com/openai/universe.git
Клонирование в «universe»…
remote: Counting objects: 1121, done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 1121 (delta 19), reused 0 (delta 0), pack-reused 1081
Получение объектов: 100% (1121/1121), 1.30 MiB | 312.00 KiB/s, готово.
Определение изменений: 100% (658/658), готово.
Проверка соединения… готово.
name@name-System-Product-Name:~/source$ cd universe
name@name-System-Product-Name:~/source/universe$ sudo pip install -e .
The directory '/home/name/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/name/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///home/name/source/universe
Requirement already satisfied: autobahn>=0.16.0 in /usr/local/lib/python2.7/dist-packages (from universe==0.21.2)
Requirement already satisfied: docker-py==1.10.3 in /usr/local/lib/python2.7/dist-packages (from universe==0.21.2)
Requirement already satisfied: docker-pycreds==0.2.1 in /usr/local/lib/python2.7/dist-packages (from universe==0.21.2)
Collecting fastzbarlight>=0.0.13 (from universe==0.21.2)
  Downloading fastzbarlight-0.0.14.tar.gz (728kB)
    100% |████████████████████████████████| 737kB 1.2MB/s 
Collecting go-vncdriver>=0.4.8 (from universe==0.21.2)
  Downloading go_vncdriver-0.4.19.tar.gz (638kB)
    100% |████████████████████████████████| 645kB 1.3MB/s 
Requirement already satisfied: gym>=0.7.0 in /usr/local/lib/python2.7/dist-packages (from universe==0.21.2)
Requirement already satisfied: Pillow>=3.3.0 in /usr/local/lib/python2.7/dist-packages (from universe==0.21.2)
Collecting PyYAML>=3.12 (from universe==0.21.2)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 2.2MB/s 
Requirement already satisfied: six>=1.10.0 in /usr/lib/python2.7/dist-packages (from universe==0.21.2)
Collecting twisted>=16.5.0 (from universe==0.21.2)
  Downloading Twisted-16.6.0.tar.bz2 (3.0MB)
    100% |████████████████████████████████| 3.0MB 368kB/s 
Collecting ujson>=1.35 (from universe==0.21.2)
  Downloading ujson-1.35.tar.gz (192kB)
    100% |████████████████████████████████| 194kB 2.7MB/s 
Requirement already satisfied: txaio>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from autobahn>=0.16.0->universe==0.21.2)
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from docker-py==1.10.3->universe==0.21.2)
Requirement already satisfied: requests<2.11,>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from docker-py==1.10.3->universe==0.21.2)
Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python2.7/dist-packages (from docker-py==1.10.3->universe==0.21.2)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /usr/lib/python2.7/dist-packages (from docker-py==1.10.3->universe==0.21.2)
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from go-vncdriver>=0.4.8->universe==0.21.2)
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python2.7/dist-packages (from gym>=0.7.0->universe==0.21.2)
Requirement already satisfied: olefile in /usr/local/lib/python2.7/dist-packages (from Pillow>=3.3.0->universe==0.21.2)
Requirement already satisfied: zope.interface>=3.6.0 in /usr/lib/python2.7/dist-packages (from twisted>=16.5.0->universe==0.21.2)
Collecting constantly>=15.1 (from twisted>=16.5.0->universe==0.21.2)
  Downloading constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from twisted>=16.5.0->universe==0.21.2)
  Downloading incremental-16.10.1-py2.py3-none-any.whl
Installing collected packages: fastzbarlight, go-vncdriver, PyYAML, constantly, incremental, twisted, ujson, universe
  Running setup.py install for fastzbarlight ... error
    Complete output from command /usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ntqiYc/fastzbarlight/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wBwLjF-record/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'optional'
      warnings.warn(msg)
    running install
    running build
    error: [Errno 13] Permission denied
    
    ----------------------------------------
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ntqiYc/fastzbarlight/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wBwLjF-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ntqiYc/fastzbarlight/
name@name-System-Product-Name:~/source/universe$ 

### Versions
Please include the result of running
```
$ uname -a ; python --version; pip show universe gym tensorflow numpy go-vncdriver Pillow
```
$ uname -a ; python --version; pip show universe gym tensorflow numpy go-vncdriver Pillow
Linux name-System-Product-Name 4.4.0-43-generic #63-Ubuntu SMP Wed Oct 12 13:48:03 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.12
Name: gym
Version: 0.7.3
Summary: The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.
Home-page: https://github.com/openai/gym
Author: OpenAI
Author-email: gym@openai.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: numpy, requests, six, pyglet
---
Name: tensorflow
Version: 0.12.1
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: mock, numpy, protobuf, wheel, six
---
Name: numpy
Version: 1.11.0
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@scipy.org
License: BSD
Location: /usr/lib/python2.7/dist-packages
Requires: 
---
Name: Pillow
Version: 4.0.0
Summary: Python Imaging Library (Fork)
Home-page: http://python-pillow.org
Author: Alex Clark (Fork Author)
Author-email: aclark@aclark.net
License: Standard PIL License
Location: /usr/local/lib/python2.7/dist-packages
Requires: olefile

**Comment by iHateInventNames** [comment]
It is tricky to install Universe. Please, help, someone.

**Comment by tlbtlbtlb** [comment]
If you're getting a permission denied error when using `pip install`, something is wrong with your Python installation, or perhaps it's a shared machine where you don't have write access to /usr/local.

Using Anaconda Python will make it easier. https://www.continuum.io/downloads

**Comment by iHateInventNames** [comment]
Should someone try this again using Ubuntu fresh installation?

**Comment by iHateInventNames** [comment]
https://packaging.python.org/distributing/#install-requires
