### ISSUE TITLE
Registering custom Docker images with N64 emulator

### ISSUE THREAD

**Issue by aldrinabastillas** [openai/universe#145]
Hi,

I created a Docker image with a N64 emulator following the second example (Firefox over VNC) from [Docker's references](https://docs.docker.com/engine/reference/builder/#/dockerfile-examples).

**Do I still need to wrap the Docker image with Universe's VNCEnv object?**

This is what I've done so far:

In Universe/universe/__init__.py, I registered the game
```
register(
    id='n64.SSB64-v0',
    entry_point='universe.wrappers:WrappedVNCEnv',
    tags={
        'vnc': True,
        'runtime': 'n64-emu',
        'wrapper_config.TimeLimit.max_episode_steps': 10**7,
        },
    )
```

In Universe/universe/runtimes/__init__.py, I registered a new runtime for my docker image
```
register_runtime(
    id='n64-emu',
    kind='docker',
    image='<dockerUserName>/<dockerImageName>',
    host_config={
        'privileged': True,
        'cap_add': ['SYS_ADMIN'],
        'ipc_mode': 'host'
    }
)
```

When I run the example from the tutorial substituting 'flashgames.DuskDrive-v0' with 'n64.SSB64-v0' I get these messages

```
Rewarder server localhost:15900 did not come up yet (error: [Errno 61] Connection refused). Sleeping for 1s.
Rewarder server localhost:15900 did not come up within 30s
```

Please let me know if I am approaching this the wrong way, thanks!!

**Comment by tlbtlbtlb** [comment]
To be a remote environment for universe, it needs to provide both a VNC server and a rewarder server. The rewarder server accepts connections on port 15900 and sends a stream of rewards (usually the change in game score), and the game-over indication (which causes env.step to return with done=True). It also does manages the session, letting the agent specify which environment it wants. The rewarder protocol is complicated and undocumented, so it's not an easy project to make a new remote env. The universe side of the code is in universe/rewarder/*.py.

**Comment by aldrinabastillas** [comment]
Makes sense, thanks for the quick reply!
