### ISSUE TITLE
Where is the convolutional neural network-based OCR model

### ISSUE THREAD

**Issue by nojvek** [openai/universe#146]
I'd like to learn how this was implemented and how to build a custom OCR. I'm trying to hunt where this is implemented

**Comment by tlbtlbtlb** [comment]
It's baked into the docker images and the source hasn't been released or documented yet.

**Comment by rogaha** [comment]
@tlbtlbtlb are the `docker images` publicly available? if yes, can you please point me their location?

**Comment by tlbtlbtlb** [comment]
`docker pull quay.io/openai/universe.flashgames:0.20.26` will download the image.
See https://docs.docker.com/engine/getstarted/step_four/#step-4-run-your-new-docker-whale for how to make use of images.

**Comment by cantren** [comment]
@rogaha Sorry this isn't more clearly organized. These are my 100% unoffical WIP working-notes that I've gathered from poking around inside the docker container: https://pastebin.com/Q0jDcSHX

The formatting looked terrible so I uploaded them to pastebin instead.

**Comment by nojvek** [comment]
That's amazing. Thanks for writing that.

> looking through some of the resulting files. It looks like many of these
games have a 0.png, 1.png, ... , 9.png digit template that is being used
with python-opencv, tensorflow, and template matching to recognize the
score of the flashgame from a game screen-capture.

I was expecting a trained cnn  to handle all game scores but this is
probably simpler, faster and more accurate.

**Comment by cantren** [comment]
No problem. I've been meaning to take a look at the contents of some of the .tar.gz files located in the: "/app/universe-envs/flashgames/build/git-lfs/" directory. Got around to doing so just now.

You can move them out of the docker image for inspection by executing "$ docker cp [dockerid]:/app/universe-envs/flashgames/build/git-lfs/flashgames.[env name]-v0.tar.gz ~/flashgames.[env name]-v0.tar.gz". 

These .tar.gz files appear to contain the environment specific configuration files necessary for Universe to automate interaction with them.

**Comment by rogaha** [comment]
@cantren thanks for adding the `notes`. Do you still have them (page removed https://pastebin.com/Q0jDcSHX)?

**Comment by cantren** [comment]
@rogaha I do not. I don't believe that I backed them up anywhere other than pastebin and I'm pretty sure I didn't put an expiration on that document.

Does anyone have a copy saved?

**Comment by unixpickle** [comment]
Any update on this? It would be good if the container was open source so people could contribute to the stuff inside.

**Comment by cantren** [comment]
I'm a little bit confused on why flash games work even without nvidia-docker. Doesn't flash run off the GPU?

Would it be possible for the browser to be compiled with WebGL support? I get a "Sorry, Your Browser doesn't support WebGL!" error when I attempt to load a three.js game from inside the docker container.

**Comment by unixpickle** [comment]
@cantren pretty sure Flash can run fine on the CPU.
