### ISSUE TITLE
_iconv not found while importing universe

### ISSUE THREAD

**Issue by Saxamos** [openai/universe#151]
Got a problem while importing universe: 

>>> import universe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "universe/__init__.py", line 22, in <module>
    from universe import error, envs
  File "universe/envs/__init__.py", line 1, in <module>
    import universe.envs.vnc_env
  File "universe/envs/vnc_env.py", line 10, in <module>
    from universe.envs import diagnostics
  File "universe/envs/diagnostics.py", line 2, in <module>
    import fastzbarlight
  File "/Users/samuelrochette/anaconda/lib/python2.7/site-packages/fastzbarlight/__init__.py", line 7, in <module>
    from ._zbarlight import zbar_code_scanner
ImportError: dlopen(/Users/samuelrochette/anaconda/lib/python2.7/site-packages/fastzbarlight/_zbarlight.so, 2): Symbol not found: _iconv
  Referenced from: /Users/samuelrochette/anaconda/lib/python2.7/site-packages/fastzbarlight/_zbarlight.so
  Expected in: flat namespace
 in /Users/samuelrochette/anaconda/lib/python2.7/site-packages/fastzbarlight/_zbarlight.so
Please include the result of running

```
$ uname -a ; python --version; pip show universe gym tensorflow numpy go-vncdriver Pillow
```
Darwin * 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
Python 2.7.13 :: Anaconda 4.3.0 (x86_64)
Name: universe
Version: 0.21.2
Summary: Universe: a software platform for measuring and training an AI's general intelligence across the world's supply of games, websites and other applications.
Home-page: https://github.com/openai/universe
Author: OpenAI
Author-email: universe@openai.com
License: UNKNOWN
Location: /Users/myname/Documents/universe
Requires: autobahn, docker-py, docker-pycreds, fastzbarlight, go-vncdriver, gym, Pillow, PyYAML, six, twisted, ujson
---
Name: gym
Version: 0.7.3
Summary: The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.
Home-page: https://github.com/openai/gym
Author: OpenAI
Author-email: gym@openai.com
License: UNKNOWN
Location: /Users/myname/anaconda/lib/python2.7/site-packages
Requires: numpy, pyglet, requests, six
---
Name: numpy
Version: 1.11.3
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@scipy.org
License: BSD
Location: /Users/myname/anaconda/lib/python2.7/site-packages
Requires:
---
Name: go-vncdriver
Version: 0.4.19
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /Users/myname/anaconda/lib/python2.7/site-packages
Requires: numpy
---
Name: Pillow
Version: 4.0.0
Summary: Python Imaging Library (Fork)
Home-page: http://python-pillow.org
Author: Alex Clark (Fork Author)
Author-email: aclark@aclark.net
License: Standard PIL License
Location: /Users/myname/anaconda/lib/python2.7/site-packages
Requires: olefile

**Comment by mikelseverson** [comment]
Also getting this error, same package versions using anaconda with python 3.6.
On macOS sierra.

**Comment by tlbtlbtlb** [comment]
Same as https://github.com/openai/universe/issues/139

**Comment by MarcGreve** [comment]
Same

**Comment by Martellacci** [comment]
Same

**Comment by Martellacci** [comment]
same
