### ISSUE TITLE
import universe facing exception

### ISSUE THREAD

**Issue by maheshwarLigade** [openai/universe#156]
(First, please check https://github.com/openai/universe/wiki/Solutions-to-common-problems for solutions to many common problems)

### Versions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maheshwarligade/Documents/universe/universe/__init__.py", line 22, in <module>
    from universe import error, envs
  File "/Users/maheshwarligade/Documents/universe/universe/envs/__init__.py", line 1, in <module>
    import universe.envs.vnc_env
  File "/Users/maheshwarligade/Documents/universe/universe/envs/vnc_env.py", line 11, in <module>
    from universe.envs import diagnostics
  File "/Users/maheshwarligade/Documents/universe/universe/envs/diagnostics.py", line 2, in <module>
    import fastzbarlight
  File "/Users/maheshwarligade/Documents/conda/anaconda/lib/python3.5/site-packages/fastzbarlight/__init__.py", line 7, in <module>
    from ._zbarlight import zbar_code_scanner
ImportError: dlopen(/Users/maheshwarligade/Documents/conda/anaconda/lib/python3.5/site-packages/fastzbarlight/_zbarlight.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libiconv.2.dylib
  Referenced from: /Users/maheshwarligade/Documents/conda/anaconda/lib/python3.5/site-packages/fastzbarlight/_zbarlight.cpython-35m-darwin.so
  Reason: Incompatible library version: _zbarlight.cpython-35m-darwin.so requires version 8.0.0 or later, but libiconv.2.dylib provides version 7.0.0
```
$ uname -a ; python --version; pip show universe gym tensorflow numpy go-vncdriver Pillow
```
Python 3.5.0 :: Anaconda custom (x86_64)
Name: universe
Version: 0.21.2
Summary: Universe: a software platform for measuring and training an AI's general intelligence across the world's supply of games, websites and other applications.
Home-page: https://github.com/openai/universe
Author: OpenAI
Author-email: universe@openai.com
License: UNKNOWN
Location: /Users/maheshwarligade/Documents/universe
Requires: autobahn, docker-py, docker-pycreds, fastzbarlight, go-vncdriver, gym, Pillow, PyYAML, six, twisted, ujson
---
Name: gym
Version: 0.7.3
Summary: The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.
Home-page: https://github.com/openai/gym
Author: OpenAI
Author-email: gym@openai.com
License: UNKNOWN
Location: /Users/maheshwarligade/Documents/conda/anaconda/lib/python3.5/site-packages
Requires: pyglet, requests, six, numpy
---
Name: numpy
Version: 1.11.3
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@scipy.org
License: BSD
Location: /Users/maheshwarligade/Documents/conda/anaconda/lib/python3.5/site-packages
Requires: 
---
Name: go-vncdriver
Version: 0.4.19
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /Users/maheshwarligade/Documents/conda/anaconda/lib/python3.5/site-packages
Requires: numpy
---
Name: Pillow
Version: 3.4.2
Summary: Python Imaging Library (Fork)
Home-page: http://python-pillow.org
Author: Alex Clark (Fork Author)
Author-email: aclark@aclark.net
License: Standard PIL License
Location: /Users/maheshwarligade/Documents/conda/anaconda/lib/python3.5/site-packages
Requires:

**Comment by tlbtlbtlb** [comment]
Same as https://github.com/openai/universe/issues/139
