### ISSUE TITLE
How to use local docker image? 

### ISSUE THREAD

**Issue by paive** [openai/universe#157]
Hi.
When I run my first agent, it is very slow pulling images automatically by the program. Then I downloaded the docker image `openai/universe.flashgames` with latest version  from docker hub by myself.  However it still pull the docker image when I run the program. And I want to know is there any solution to use the local docker image.

**Comment by tarvos21** [comment]
Hi, @paive, I have the same situation with you, slow pulling image of flash games, unfortunately Docker does not support proxies, so may I ask how do you finally make it?

**Comment by paive** [comment]
Hi, have you solved this problem? If not, you can refer next steps.

First, download the universe flash games images from docker hub,  you can use 'docker images' in terminal to view the repository and tag. Maybe the repository is 'openai/universe.flashgames' and tag is 'latest' or '0.20.21' or any others.

Second, make sure the version of container that would be created by universe, just run the example of universe and you can find one line of output is 'Creating container: image=quay.io/openai/universe.flashgames:0.20.21', maybe the tag is others.

Third, modify the repository and tag according to second step, for example is use 'docker tag openai/universe.flashgames:latest  quay.io/openai/universe.flashgames:0.20.21'.

Anyway, it is essentially rename the image and its tag.

If it does not help you solve the problem, welcome for further discussion.

________________________________
发件人: Bingo Du <notifications@github.com>
发送时间: 2017年3月21日 11:35:21
收件人: openai/universe
抄送: paive; Mention
主题: Re: [openai/universe] How to use local docker image? (#157)


Hi, @paive<https://github.com/paive>, I have the same situation with you, slow pulling image of flash games, unfortunately Docker does not support proxies, so may I ask how do you finally make it?

―
