### ISSUE TITLE
Cannot stop logger printing to console in flash environments

### ISSUE THREAD

**Issue by iulialexandra** [openai/universe#168]
### Expected behavior
I would like to be able to turn off the logger output to console when running a flash environment. I tried logger.disable, logger.propagate on the root logger as well as all loggers used by universe and gym, as well as changing verbosity as shown in the _diagnostic-agent_ example.
### Actual behavior
Nothing makes a difference, loggers are still at level INFO and still print out everything to console. 
### Versions
```

88-Ubuntu SMP Wed Mar 8 16:34:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Python 3.6.0 :: Anaconda custom (64-bit)
Name: universe
Version: 0.21.4.dev0
---
Name: gym
Version: 0.7.4
---
Name: tensorflow
Version: 1.0.0
---
Name: numpy
Version: 1.12.0
---
Name: go-vncdriver
Version: 0.4.19
---
Name: Pillow
Version: 4.0.0
```

**Comment by tlbtlbtlb** [comment]
The most voluminous logs are from the Docker container. It's useful to see when something in the container is breaking, but once you have it working it the logging makes it impossible to use the REPL.

I checked in a proposed fix on a branch. Check out the https://github.com/openai/universe/tree/tlb-less-logging branch and run `export OPENAI_REMOTE_VERBOSE=0` before running python.

**Comment by iulialexandra** [comment]
This works great, thanks a lot!
