### ISSUE TITLE
Import universe Error when try to run the remote

### ISSUE THREAD

**Issue by Akagilnc** [openai/universe#179]
(First, please check https://github.com/openai/universe/wiki/Solutions-to-common-problems for solutions to many common problems)

### Expected behavior
run the remote
### Actual behavior
run error
### Versions
Please include the result of running
```
File "Index.py", line 2, in <module>
    import universe
  File "/Users/deronlee/PycharmProjects/AI_Meeting/universe/universe/__init__.py", line 22, in <module>
    from universe import error, envs
  File "/Users/deronlee/PycharmProjects/AI_Meeting/universe/universe/envs/__init__.py", line 1, in <module>
    import universe.envs.vnc_env
  File "/Users/deronlee/PycharmProjects/AI_Meeting/universe/universe/envs/vnc_env.py", line 19, in <module>
    import go_vncdriver
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/go_vncdriver/__init__.py", line 9, in <module>
    from go_vncdriver.go_vncdriver import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/go_vncdriver/go_vncdriver.so, 2): no suitable image found.  Did find:
        /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/go_vncdriver/go_vncdriver.so: overlapping segments
```
```
$ uname -a ; python --version; pip show universe gym tensorflow numpy go-vncdriver Pillow
```
Darwin DeronLees-MacBook-Pro.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

Python 3.6.0

Name: universe
Version: 0.21.5
Summary: Universe: a software platform for measuring and training an AI's general intelligence across the world's supply of games, websites and other applications.
Home-page: https://github.com/openai/universe
Author: OpenAI
Author-email: universe@openai.com
License: UNKNOWN
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: autobahn, docker-py, docker-pycreds, fastzbarlight, go-vncdriver, gym, Pillow, PyYAML, six, twisted, ujson
---
Name: gym
Version: 0.8.1
Summary: The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.
Home-page: https://github.com/openai/gym
Author: OpenAI
Author-email: gym@openai.com
License: UNKNOWN
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: numpy, requests, six, pyglet
---
Name: numpy
Version: 1.12.1
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@scipy.org
License: BSD
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: 
---
Name: go-vncdriver
Version: 0.4.19
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: numpy
---
Name: Pillow
Version: 4.1.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author: Alex Clark (Fork Author)
Author-email: aclark@aclark.net
License: Standard PIL License
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: olefile
---

**Comment by tlbtlbtlb** [comment]
This is due to compiling go_vncdriver for a different version of Python than you're running. You can fix it by `pip install --ignore-installed go_vncdriver`

**Comment by DeronLee** [comment]
@tlbtlbtlb It wasn't worked.
I fixed it by doing this:
```
$ git clone https://github.com/openai/go-vncdriver.git
$ cd go-vncdriver
$ python build.py
$ pip install -e .
```
```
brew install libjpeg-turbo
```
and I install the golang from their site.

after that it worked fine
