### ISSUE TITLE
Provide list of available actions in documentation

### ISSUE THREAD

**Issue by mijoharas** [openai/universe#2]
The list of available `KeyEvent`s and the format of `PointerEvent`s should be available and visible in the documentation (if they are please close this ticket, I couldn't find them).

KeyEvents appear to be here: https://github.com/openai/universe/blob/a7944e65446a5484e5011f048558f312e907da61/universe/vncdriver/constants.py#L85-L170

And the format of pointer events appears to be `vnc.PointerEvent(x, y, button_mask)` but this is just from reading the code.

For `KeyEvent`s should it be `spaces.KeyEvent.by_name('c', down=True)` I'm not sure what format to use?

**Comment by au-re** [comment]
Is it also possible to see what KeyEvents are allowed for each environment?
