### ISSUE TITLE
Does this project have a website?

### ISSUE THREAD

**Issue by JINKEHE** [openai/universe#207]
I'd like to see some basic introduction of OpenAI Universe. However, when I enter https://universe.openai.com, the browser is always redirected to this github page.

**Comment by yeeeeeeeeee** [comment]
Happens the same to me. Some weeks ago I entered the website universe.openai.com but now seems to be closed. I don't know what happens

**Comment by Kyogawa** [comment]
The only one I found is this:
https://blog.openai.com/universe/

**Comment by sunshineclt** [comment]
Seems OpenAI has abandoned this project?

**Comment by zabatani** [comment]
@sunshineclt, can anyone verify this?

**Comment by sunshineclt** [comment]
@zabatani I don't know.

**Comment by MarxSoul55** [comment]
At least it *used* to have a website—I remember actually visiting it and looking at the different environments that were available, but I can't remember when. It was *at least* months ago, or perhaps a year or two.

I did a little research and found [this thread on Reddit](https://www.reddit.com/r/MachineLearning/comments/6zvlm2/d_openai_closing_down_gym_toolkit_website/) about a related issue.
