### ISSUE TITLE
is the project abandoned?

### ISSUE THREAD

**Issue by kirk86** [openai/universe#218]
Hello everyone and thanks for open sourcing universe to the public. I just have two generic questions. 

1. Is the project abandoned?
2. Are the issues presented [here](https://blog.aqnichol.com/2017/06/11/why-im-remaking-openai-universe/) fixed yet or not? If not why haven't someone yet contacted the author of [this](https://github.com/unixpickle/muniverse) to contribute his solution to universe?
3. Is it possible to integrate deep mind's [lab](https://github.com/deepmind/lab) into gym?

Thanks in advance!

**Comment by pascalwhoop** [comment]
Seems pretty dead to me. Gym is still alive though. I wonder what’s going on in the team that this project is so utterly abandoned without commenting or giving notification about it. Pulse says last activity was in may last year.

**Comment by unixpickle** [comment]
Hi, I'm the author of the blog post @kirk86 linked in his second point, and I now work at OpenAI. As Ilya mentioned in [this old reddit thread](https://www.reddit.com/r/MachineLearning/comments/6jjrk3/d_why_im_remaking_openai_universe/), we have something better in the works.

Meta-learning is an important area of research, and we want solid environments for it. Universe just didn't seem like the best way to get those environments.

**Comment by pascalwhoop** [comment]
@unixpickle can you do a clear announcement and remove universe from the website/ put a clear “deprecated” banner in the readme? You and your team have a lot of people following you so beware that leaving a project like this in limbo for months causes lots of head scratching

**Comment by kirk86** [comment]
> causes lots of head scratching

I like that term, and in the years of hype-learning that we're leaving causes a lot of pondering about where OpenAI is heading at.

**Comment by frogoscar** [comment]
@unixpickle Hello, thanks for your reply. But https://github.com/unixpickle/muniverse is no longer maintained neither. OpenAI is just abandoning Universe like this ？Without any official statement... Sad to see this.

**Comment by Fohlen** [comment]
Please also mark the repo as _"archived"_ on GitHub so further users won't stumble upon this ticket ny longer
