### ISSUE TITLE
Running  --> import universe results in the following

### ISSUE THREAD

**Issue by shubhamkumar13** [openai/universe#232]
`ModuleNotFoundError                      Traceback (most recent call last)
<ipython-input-2-917a504b1f6f> in <module>()
----> 1 import universe

~/universe/universe/__init__.py in <module>()
     18 from gym.envs.registration import register
     19 
---> 20 import universe.scoreboard
     21 import universe.configuration
     22 from universe import error, envs

~/universe/universe/scoreboard/__init__.py in <module>()
----> 1 from gym.benchmarks import scoring
      2 from gym.benchmarks import register_benchmark
      3 
      4 register_benchmark(
      5     id='Atari7VNC-v0',

ModuleNotFoundError: No module named 'gym.benchmarks'
`

**Comment by twerkmeister** [comment]
see #228
