### ISSUE TITLE
Unable to launch example environment

### ISSUE THREAD

**Issue by Givemeyourgits** [openai/universe#25]
I have universe installed and all the dependencies.  When I try to run the example script it starts, I am able to VNC, but I never see anything, and a few minutes later it disconnects VNC.

Here is the universe log I got.

[universe.txt](https://github.com/openai/universe/files/633402/universe.txt)

**Comment by gdb** [comment]
This looks like the same as #6. Should be fixed later today!

**Comment by Givemeyourgits** [comment]
Same issue with latest commit.  It attempts 10 times to try to launch chrome process then disconnects VNC and gives up (VNC connects but just shows black screen).

**Comment by Givemeyourgits** [comment]
Updated again, same issue.  Still can't launch it.

**Comment by gdb** [comment]
What's the docker invocation you're using to run the enviromnent?

**Comment by Givemeyourgits** [comment]
I am just running the example code into a REPL session.

This is what I see from the output.

`[2016-12-08 01:29:33,338] [0] Creating container: image=quay.io/openai/universe.flashgames:0.20.3. Run the same thing by hand as: docker run -p 5900:5900 -p 15900:15900 --ipc host --privileged --cap-add SYS_ADMIN quay.io/openai/universe.flashgames:0.20.3`

**Comment by gdb** [comment]
Got it. Can you paste me full logs, of: terminal output and then the universe.log?

Also, mind trying `docker run -p 5900:5900 -p 15900:15900 --ipc host --privileged --cap-add SYS_ADMIN quay.io/openai/universe.flashgames:0.20.3 run -e flashgames.DuskDrive-v0` and paste me the logs from that?

What platform are you on? What docker daemon are you using?

**Comment by Givemeyourgits** [comment]
Debian Jesse
Just did the basic docker install and ran 'service docker start'

[Using Example Code]
[universe-27531.txt](https://github.com/openai/universe/files/638616/universe-27531.txt)
[output.txt](https://github.com/openai/universe/files/638618/output.txt)

[Output of docker command requested]
[output2.txt](https://github.com/openai/universe/files/638621/output2.txt)

**Comment by gdb** [comment]
Ah — what docker version are you running? (Output of `docker version`)

**Comment by Givemeyourgits** [comment]
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64

**Comment by gdb** [comment]
Ok, you have a pretty up-to-date Docker. We haven't tested on Jessie, but I'm not sure I'd expect there to be issues there. I assume you don't have weirdly limited CPU or something that could cause the container to run abnormally slowly?

Two more things to try:

1. I pushed a build, 0.20.5-dev1, which has a 1min timeout. Try `docker run -p 5900:5900 -p 15900:15900 --ipc host --privileged --cap-add SYS_ADMIN quay.io/openai/universe.flashgames:0.20.5-dev1 run -e flashgames.DuskDrive-v0`. I don't expect it to make a difference, but worth trying.
2. I think this is a Selenium issue. Can you try the following. (If it succeeds, open up your VNC viewer to make sure the browser is open.)

```
$ docker run -ti -p 5900:5900 -p 15900:15900 --ipc host --privileged --cap-add SYS_ADMIN quay.io/openai/universe.flashgames:0.20.3 shell
...
root@2426fbfef3c5:/app/universe-envs/flashgames# python
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver; webdriver.Chrome()
<selenium.webdriver.chrome.webdriver.WebDriver (session="f70c7ade061b4b56a833a53e75d3d55f")>```

**Comment by Givemeyourgits** [comment]
1.  No Difference
2.  Still black screen

As for CPU, it's an 8 core Xeon with 48GB ram and 0.23 load average.  So it has lots of resources to work with.

**Comment by gdb** [comment]
Ok great, so it is indeed selenium. I think this won't be our bug, though maybe we can help work around it. I assume that step 2 doesn't return, and just hangs?

Let me look for a simpler test case.

**Comment by Givemeyourgits** [comment]
It seems to just run.  No output. No feedback.

**Comment by gdb** [comment]
Yeah, that means it's hanging. I think there's a way to get logs out of Selenium. Here's a much smaller test case though:

```docker run -v /dev/shm:/dev/shm --cap-add SYS_ADMIN --privileged -ti quay.io/openai/selenium```

And then run `xvfb-run python3` and `from selenium import webdriver; webdriver.Chrome()`. If it works, you should get output like the below:

```root@577b5c6f10ba:/# xvfb-run python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from selenium import webdriver; webdriver.Chrome()
<selenium.webdriver.chrome.webdriver.WebDriver (session="0417386266dda5ae68996bcc627dfd81")>```

In case you're curious, the Dockerfile is here:

[Dockerfile](https://github.com/openai/universe/files/640253/Dockerfile.txt)

**Comment by Givemeyourgits** [comment]
Same thing, no output.  Just sits there with cursor on next line.

![securecrt_2016-12-08_13-31-07](https://cloud.githubusercontent.com/assets/1454872/21022445/a0b3e742-bd4a-11e6-810c-a66170001b5b.png)

**Comment by gdb** [comment]
Ok great. Can you `docker exec` into the container and then run `ps aux`?

**Comment by Givemeyourgits** [comment]
After a minute or so, I got this:

'Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 3.16.0-4-amd64 x86_64)'

**Comment by gdb** [comment]
OK, great. That's what I was hoping.

I've figured out how to get logs out of Selenium; added this line to the Dockerfile: ```RUN mv /usr/local/bin/chromedriver /usr/local/bin/chromedriver.real &&\
  echo "#!/bin/sh\nexec /usr/local/bin/chromedriver.real --verbose --log-path=/tmp/log.txt \"\$@\"" > /usr/local/bin/chromedriver &&\
  chmod 755 /usr/local/bin/chromedriver```

So now if you re-pull the image (`docker pull quay.io/openai/selenium`) and re-run the example, there should be a `/tmp/log.txt` with the actual error.

**Comment by Givemeyourgits** [comment]
I get the following error when running the first part:

`-bash: !/bin/sh\nexec: event not found`

**Comment by gdb** [comment]
Sorry, to be clear, you don't need to run the line from the Dockerfile above — you should just `docker pull quay.io/openai/selenium` and then run the `python3` line.

**Comment by Givemeyourgits** [comment]
Sorry about that, was being dumb.

`[1.000][INFO]: COMMAND InitSession {
   "desiredCapabilities": {
      "browserName": "chrome",
      "chromeOptions": {
         "args": [  ],
         "extensions": [  ]
      },
      "javascriptEnabled": true,
      "platform": "ANY",
      "version": ""
root@724adbaa6de4:/tmp# head log.txt 100 
==> log.txt <==
[1.000][INFO]: COMMAND InitSession {
   "desiredCapabilities": {
      "browserName": "chrome",
      "chromeOptions": {
         "args": [  ],
         "extensions": [  ]
      },
      "javascriptEnabled": true,
      "platform": "ANY",
      "version": ""
head: cannot open '100' for reading: No such file or directory
root@724adbaa6de4:/tmp# head -100 log.txt
[1.000][INFO]: COMMAND InitSession {
   "desiredCapabilities": {
      "browserName": "chrome",
      "chromeOptions": {
         "args": [  ],
         "extensions": [  ]
      },
      "javascriptEnabled": true,
      "platform": "ANY",
      "version": ""
   },
   "requiredCapabilities": {

   }
}
[1.001][INFO]: Populating Preferences file: {
   "alternate_error_pages": {
      "enabled": false
   },
   "autofill": {
      "enabled": false
   },
   "browser": {
      "check_default_browser": false
   },
   "distribution": {
      "import_bookmarks": false,
      "import_history": false,
      "import_search_engine": false,
      "make_chrome_default_for_user": false,
      "show_welcome_page": false,
      "skip_first_run_ui": true
   },
   "dns_prefetching": {
      "enabled": false
   },
   "profile": {
      "content_settings": {
         "pattern_pairs": {
            "https://*,*": {
               "media-stream": {
                  "audio": "Default",
                  "video": "Default"
               }
            }
         }
      },
      "default_content_setting_values": {
         "geolocation": 1
      },
      "default_content_settings": {
         "geolocation": 1,
         "mouselock": 1,
         "notifications": 1,
         "popups": 1,
         "ppapi-broker": 1
      },
      "password_manager_enabled": false
   },
   "safebrowsing": {
      "enabled": false
   },
   "search": {
      "suggest_enabled": false
   },
   "translate": {
      "enabled": false
   }
}
[1.001][INFO]: Populating Local State file: {
   "background_mode": {
      "enabled": false
   },
   "ssl": {
      "rev_checking": {
         "enabled": false
      }
   }
}
[1.001][INFO]: Launching chrome: /opt/google/chrome/google-chrome --disable-background-networking --disable-client-side-phishing-detection --disable-component-update --disable-default-apps --disable-hang-monitor --disable-infobars --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-logging --ignore-certificate-errors --load-extension=/tmp/.org.chromium.Chromium.jZz1kB/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12445 --safebrowsing-disable-auto-update --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.KesYsp data:,
[1.001][DEBUG]: DevTools request: http://localhost:12445/json/version
[1.426][DEBUG]: DevTools request failed
[1.477][DEBUG]: DevTools request: http://localhost:12445/json/version
[1.477][DEBUG]: DevTools request failed
[1.527][DEBUG]: DevTools request: http://localhost:12445/json/version
[1.528][DEBUG]: DevTools request failed
[1.578][DEBUG]: DevTools request: http://localhost:12445/json/version
[1.578][DEBUG]: DevTools request failed
[1.629][DEBUG]: DevTools request: http://localhost:12445/json/version
[1.629][DEBUG]: DevTools request failed
[1.679][DEBUG]: DevTools request: http://localhost:12445/json/version
[1.680][DEBUG]: DevTools request failed
[1.730][DEBUG]: DevTools request: http://localhost:12445/json/version
[1.730][DEBUG]: DevTools request failed
[1.781][DEBUG]: DevTools request: http://localhost:12445/json/version
[1.781][DEBUG]: DevTools request failed
[1.831][DEBUG]: DevTools request: http://localhost:12445/json/version
[1.832][DEBUG]: DevTools request failed
[1.882][DEBUG]: DevTools request: http://localhost:12445/json/version
[1.882][DEBUG]: DevTools request failed
...
[60.869][DEBUG]: DevTools request failed
[60.919][DEBUG]: DevTools request: http://localhost:12445/json/version
[60.920][DEBUG]: DevTools request failed
[60.970][DEBUG]: DevTools request: http://localhost:12445/json/version
[60.970][DEBUG]: DevTools request failed
[61.020][DEBUG]: DevTools request: http://localhost:12445/json/version
[61.021][DEBUG]: DevTools request failed
[61.024][INFO]: RESPONSE InitSession unknown error: Chrome failed to start: crashed
[61.024][DEBUG]: Log type 'driver' lost 0 entries on destruction
[61.024][DEBUG]: Log type 'browser' lost 0 entries on destruction`

**Comment by gdb** [comment]
Cool. Unfortunately not seeing the root error... wanna try uploading the whole file? The real error is maybe hiding in there somewhere.

If not, I think we'll need to move this issue to the Selenium Github project.

**Comment by Givemeyourgits** [comment]
Full log file

[log.txt](https://github.com/openai/universe/files/640369/log.txt)

**Comment by gdb** [comment]
Oh actually had another idea. Try running this:

```xvfb-run /opt/google/chrome/google-chrome --disable-background-networking --disable-client-side-phishing-detection --disable-component-update --disable-default-apps --disable-hang-monitor --disable-infobars --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-logging --ignore-certificate-errors --load-extension=/tmp/.org.chromium.Chromium.jZz1kB/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12445 --safebrowsing-disable-auto-update --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.KesYsp data:,```

On my machine:

```root@997d84777724:/# /opt/google/chrome/google-chrome --disable-background-networking --disable-client-side-phishing-detection --disable-component-update --disable-default-apps --disable-hang-monitor --disable-infobars --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-logging --ignore-certificate-errors --load-extension=/tmp/.org.chromium.Chromium.jZz1kB/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12445 --safebrowsing-disable-auto-update --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.KesYsp data:,
[265:265:1208/191152:ERROR:browser_main_loop.cc(265)] Gtk: cannot open display:
root@997d84777724:/# xvfb-run /opt/google/chrome/google-chrome --disable-background-networking --disable-client-side-phishing-detection --disable-component-update --disable-default-apps --disable-hang-monitor --disable-infobars --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-logging --ignore-certificate-errors --load-extension=/tmp/.org.chromium.Chromium.jZz1kB/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12445 --safebrowsing-disable-auto-update --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.KesYsp data:,
[296:312:1208/191153:ERROR:bus.cc(427)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[296:296:1208/191154:ERROR:desktop_window_tree_host_x11.cc(1127)] Not implemented reached in virtual void views::DesktopWindowTreeHostX11::InitModalType(ui::ModalType)

(google-chrome.real:296): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
/usr/bin/dbus-launch terminated abnormally without any error message```

**Comment by Givemeyourgits** [comment]
Illegal instruction (core dumped)

**Comment by gdb** [comment]
Well, that's interesting! Maybe playing around with the above command some more, running under gdb, etc.

It's probably worth installing Selenium / chromedriver on your machine outside of Docker and seeing if you can repro there.

**Comment by Givemeyourgits** [comment]
Is there a good test script I can use to test it once I have them installed?  Never used either of them myself.

**Comment by gdb** [comment]
Yeah, just `from selenium import webdriver; webdriver.Chrome()` should do it. You can also run Chrome directly like the above.

**Comment by Givemeyourgits** [comment]
Will give this a try and will post an update when I have.

Thanks.

**Comment by Morgan243** [comment]
I've had the same problems as @Givemeyourgits , and I've followed the suggested commands/attempts. I did notice that when trying to run chrome directly within the container using the suggested command:

```
xvfb-run /opt/google/chrome/google-chrome --disable-background-networking --disable-client-side-phishing-detection --disable-component-update --disable-default-apps --disable-hang-monitor --disable-infobars --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-logging --ignore-certificate-errors --load-extension=/tmp/.org.chromium.Chromium.jZz1kB/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12445 --safebrowsing-disable-auto-update --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.KesYsp data:,
```

that before the core dump, some more information is displayed:
```
[58:58:1209/024715:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Aborted (core dumped)
```

Searching for this sandbox error I found [another issue on github involving this error and running chromium](https://github.com/probonopd/AppImages/issues/81). I've tested adding the switch `--no-sandbox` and it appears to start chromium (no more core dump, get some gtk stuff).

I'm not too familiar with docker or the how the universe project is designed, but judging from the linked github discussion, 'sandboxing' should only be used for dev (security problems?), and it looks like users with this error need to switch to a kernel that implements the features needed for sandboxing.

**Comment by gdb** [comment]
Good find! @Givemeyourgits does that flag solve your problem too? Inside of the Flash container, we run Chrome with `--disable-gpu-sandbox --disable-setuid-sandbox`. I've prepared `universe.flashgames:0.20.5-dev2` which also adds `--no-sandbox` — give that a try and let me know if it works:

```docker run -p 5900:5900 -p 15900:15900 --ipc host --privileged --cap-add SYS_ADMIN quay.io/openai/universe.flashgames:0.20.5-dev2 run -e flashgames.DuskDrive-v0```

**Comment by pa-sword** [comment]
It renders for issue #30, let me know if I can provide anything further.

**Comment by Givemeyourgits** [comment]
Ding Ding, we have a winner!  That did it.

**Comment by gdb** [comment]
Awesome work everyone! Will roll this into the next release.

**Comment by Morgan243** [comment]
The dev2 build works for me with the supplied docker command - I went ahead and set 0.20.5-dev2 as the tag for flashgames in the runtimes.yml config and the up-arrow-only example also runs fine. So no other issues that I can see. Thanks @gdb

**Comment by mikenicholls88** [comment]
@Givemeyourgits I had the same problem, the car started, the dial was revved up and it crossed the start line and then it seemed like the AI driver took their foot off the accelerator and the car just stops and doesnt move until it times out, any clues?
