### ISSUE TITLE
Couldn't import universe without doing 'pip install -U cryptography'

### ISSUE THREAD

**Issue by nieoh** [openai/universe#26]
Got the following error after following installation steps for each aspect (Docker, making sure every version of dependency was greater than the requirement): 

```AttributeError: 'FFILibrary' object has no attribute 'Cryptography_HAS_SSL_ST'```

Doing ```pip install -U cryptography``` per [this](https://github.com/pyca/pyopenssl/issues/559) seems to fix the issue.

**Comment by alexandercbooth** [comment]
I had a similar issue on macOS and anaconda 3.5: 

`AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_STATIC_CALLBACKS'`

and was able to resolve it by uninstalling conda version of cryptography and pip install as suggested above. My error appeared to be conda related.
