### ISSUE TITLE
Limit agent to use only the mouse or keyboard

### ISSUE THREAD

**Issue by Telemakhos** [openai/universe#29]
Is there a quick way to give access only to the keyboard or the mouse? for instance, I'd like my agent to interact with a webapp *only* using the mouse...

thanks for your incredible work

**Comment by gdb** [comment]
Very easy to write — cf the following wrapper to restrict the action space (https://github.com/openai/universe/blob/master/universe/wrappers/action_space.py), and then just pare down the VNCActionSpace (https://github.com/openai/universe/blob/master/universe/spaces/vnc_action_space.py#L9).

**Comment by Telemakhos** [comment]
Awesome! thanks for the pointers!
