### ISSUE TITLE
go_vncdriver window blank for flashgames environments 

### ISSUE THREAD

**Issue by pa-sword** [openai/universe#30]
The examples agent for pong runs normally. DuskDriver-v0 opens go_vnc, fails to render for a minute and then loses TCP.

[universe.txt](https://github.com/openai/universe/files/635472/universe-11609.txt)

**Comment by jeremyschlatter** [comment]
Thanks for the logs! Not sure what's going on yet, though. Can you also attach logs from the example agent and the docker container? Easier to do if you run them as separate processes. See https://github.com/openai/universe/issues/6#issuecomment-264947599

**Comment by pa-sword** [comment]
Around 05:46:31 I have the render process up on [examples](https://github.com/openai/universe/files/635753/universe-23949.txt). As for the docker logs, `docker ps -l` claims that there isn't a container so I've tried `docker run -p 5900:5900 -p 15900:15900 --ipc host --privileged --cap-add SYS_ADMIN quay.io/openai/universe.flashgames:0.20.1`. This also runs for a minute or two before stopping: 
[docker.txt](https://github.com/openai/universe/files/635761/docker.txt). I haven't read through docker's side yet so hopefully it will have an insight.

**Comment by pa-sword** [comment]
At least it's obvious that the environment isn't starting properly. I hope it's not from something trivial like a missing dependency.

**Comment by zhourunlai** [comment]
I met the same problem running the demo code firstly, then i tried to restart the docker and run it again, that's ok now. See [http://localhost:15900/viewer/?password=openai](http://localhost:15900/viewer/?password=openai), this the same stream as the new game window.

**Comment by pa-sword** [comment]
Thanks very much for the tip, not only restarting docker but container management may have a result.

**Comment by pa-sword** [comment]
Now running [DuskDrive.py](https://github.com/openai/universe/files/637895/DuskDrive.txt), with all other containers removed from docker. First run: 
[docker-stdout.txt](https://github.com/openai/universe/files/637910/docker-stdout.txt)
[stdout.txt](https://github.com/openai/universe/files/637911/stdout.txt)
[universe.txt](https://github.com/openai/universe/files/637912/universe.txt)
After stopping and restarting docker:
[stdout-2.txt](https://github.com/openai/universe/files/637914/stout-2.txt)
[universe-2.txt](https://github.com/openai/universe/files/637916/universe-2.txt)
At a glance I don't see a difference on the restarted container.

**Comment by jeremyschlatter** [comment]
From `docker-stdout.txt`:

```
Failed to start environment with 10 consecutive attempts. Probably not going to happen.
```

This means the process in the docker container failed to start Chrome 10 consecutive times. We've seen a few causes for that. One thing to try is adding `--cap-add NET_ADMIN` to your docker command. It's also worth double-checking that your docker container isn't out of memory or disk space.

We should try to report the error message from Chrome here. The client should definitely get a better error than the server inside the container just hanging up the connection.

**Comment by jeremyschlatter** [comment]
See discussion at #25 on debugging Chrome issues

**Comment by pa-sword** [comment]
Perfectly correct, I was not cleaning docker properly. And in fact, the dev2 version in that thread is now rendering!
