### ISSUE TITLE
connection reset by peer when pulling from docker

### ISSUE THREAD

**Issue by TriRpi** [openai/universe#38]
Everytime I run the exemple script. There is a docker pulled to my system. After about an 1 hour of downloading I will get read 

    tcp 192.168.1.25:40602->54.231.120.227:443: read: connection reset by peer

I have no idea where this is coming from. Docker works fine. I am on Ubuntu 16.04.

**Comment by gdb** [comment]
Can you do `docker pull <image ID>`? It's a ~1.5G image pull from Quay, so it's not a trivial download. Fortunately you should only have to do it once.

**Comment by TriRpi** [comment]
No, this is the output from `docker pull quay.io/openai/universe.flashgames:latest`

    eekhoorn@eekhoorn-home:~$ docker pull quay.io/openai/universe.flashgames:latest
    latest: Pulling from openai/universe.flashgames

    aed15891ba52: Pull complete 
    773ae8583d14: Pull complete 
    d1d48771f782: Pull complete 
    cd3d6cd6c0cf: Pull complete 
    8ff6f8a9120c: Pull complete 
    dd8b54e91746: Downloading [==================================================>] 222.5 MB/222.5 MB
    2e5cb956f982: Download complete 
    0c93ba10c511: Download complete 
    39d8cf200333: Download complete 
    7f890b5c2ffb: Download complete 
    376798e834f8: Download complete 
    e0bf4006396b: Download complete 
    f7ab06525008: Download complete 
    3906ec9156e2: Download complete 
    9e15b01284c5: Download complete 
    bd51ef3532c1: Download complete 
    35942670c413: Download complete 
    68f2958ec854: Download complete 
    16c5a38bc1e6: Download complete 
    72d0d0234a6f: Download complete 
    29ab8bfac8ec: Download complete 
    1ffcc9378fb7: Download complete 
    77841c2a13d8: Download complete 
    574cb7190254: Download complete 
    b0bddc1896b8: Downloading [==================================================>] 57.39 MB/57.39 MB
    efa9bc0ed099: Download complete 
    8933054a3e85: Download complete 
    f7a1026fe1c3: Download complete 
    630b54a99750: Download complete 
    f921e35ae549: Downloading [==================================================>] 17.46 MB/17.46 MB
    27c5524132b0: Download complete 
    16e6b00320d2: Download complete 
    bbacebd3d128: Download complete 
    dda976fe270d: Download complete 
    daa9896abcaa: Download complete 
    4653610fdc93: Download complete 
    8f1eceb9b78e: Download complete 
    b2920e2f6f7d: Download complete 
    13a985f40bc6: Download complete 
    0e7e353c21ad: Download complete 
    db0eace683b4: Download complete 
    54e1a80841a9: Download complete 
    read tcp 192.168.1.25:52524->54.231.114.19:443: read: connection reset by peer

**Comment by TriRpi** [comment]
I recently did `docker pull /openai/universe.flashgames`. It did work, but unfortunately it isn't the whole image. When I now do `docker pull quay.io/openai/universe.flashgames` I still get `read tcp 192.168.1.25:37252->52.216.1.40:443: read: connection reset by peer`.
`

**Comment by TriRpi** [comment]
This was problably a network related issue.
