### ISSUE TITLE
docker behind proxy

### ISSUE THREAD

**Issue by kernel8liang** [openai/universe#39]
if my docker is behind a socks5 proxy, how can i download the games?

the games is download into host or docker?

**Comment by tlbtlbtlb** [comment]
The games are fetched into the docker container with git-lfs, which doesn't (yet) support socks proxies. It's on the git-lfs roadmap:  https://github.com/git-lfs/git-lfs/issues/1424.

In the meantime, you'll probably have to run it outside the firewall.

**Comment by kernel8liang** [comment]
thanks.
