### ISSUE TITLE
difficult to pull the flash games,it always halt down there

### ISSUE THREAD

**Issue by FrankSzn** [openai/universe#44]
use command "docker pull quay.io/openai/universe.flashgames:0.20.2", Does anyone have any other way to get the flash game source.

**Comment by wagonhelm** [comment]
I had the same problem and just had to ctrl-c out and try try again till everything downloaded.  But then when I launched the test script it went and downloaded the 20.1 container which seems to be downloading fine...

**Comment by FrankSzn** [comment]
how long did you use to download the flash games? @wagonhelm

**Comment by wagonhelm** [comment]
Took about 15 min for me seems different environments use different docker container versions.

**Comment by 400yk** [comment]
I have the same problem pulling from quay.io/openai/universe.flashgames, it just seems to be taking forever (for the entire night it still says "waiting"). I tried docker pulling from docker hub and it was fine. Seems a problem with the networks

**Comment by tlbtlbtlb** [comment]
See https://github.com/openai/universe/wiki/Solutions-to-common-problems#docker-wont-pull-images
