### ISSUE TITLE
env.action_space.sample() Equivalent?

### ISSUE THREAD

**Issue by wagonhelm** [openai/universe#45]
I'm just messing around with gym-core.PongDeterministic-v3 and was wondering how does one do the equivalent of a random action for the Universe agent.

**Comment by gdb** [comment]
`env.action_space.sample()` works just fine! You may want to wrap with a SafeActionSpace wrapper to avoid a fully random agent clicking around: https://github.com/openai/universe/blob/master/example/random-agent/random-agent.py#L24-L35

**Comment by wagonhelm** [comment]
Excellent, thanks.
