### ISSUE TITLE
Support getting only game frames as observations

### ISSUE THREAD

**Issue by jderehag** [openai/universe#55]
Would it be possible to support (through a wrapper or somesuch) to get only the game frame (for any environment & game)?
In other words, remove the browser and everything for the flash games.

**Comment by tlbtlbtlb** [comment]
Functions to do this are included in the agent starter kit (http://github.com/openai/universe-starter-agent). `envs.create_flash_env` creates a stack of wrappers including cropping to the flash fame.

**Comment by jderehag** [comment]
Thank you! 
But would it not make sense to add that as wrappers to universe instead of starter_agent?

**Comment by tlbtlbtlb** [comment]
There are many ways of setting up wrappers. For instance, I've compared agents on the same environments with b&w or color, scaled down or not, different frame rates, to try to get the best results. So Universe defines the environment as providing the raw pixels so people can experiment with different pre-processing stages as part of their agent.

**Comment by jderehag** [comment]
I can see the logic in that. 
But in this case, just removing the (for every agent) unnecessary data that is by definition part of the universe and not the environment seems like something every agent will want to do anyway. 
I can add this and send you a PR, unless you insist this not something you by decision want to keep outside of universe?
Just to make it clear, I am only talking about cropping here, no additional transformations..

**Comment by tlbtlbtlb** [comment]
Many universe tasks do involve the whole screen. It's just the flashgames ones where cropping makes sense.

@gdb Should we add flashgames cropping wrappers in Universe, or leave them in the starter agent?

**Comment by baoblackcoal** [comment]
@tlbtlbtlb @gdb Is it possible that agent can do some actions to set view region size and move view region(Just like rolling or narrowing eyes )? thus, observations data size will be reduced. This requires a special control of VNC.

**Comment by jderehag** [comment]
@tlbtlbtlb I would assume its any game running inside a docker container using the VNC backend right? For instance the atari games (if run through gym-core) also requires cropping eventhough in that case its just black pixels and no QR codes or anything.
But I guess this is due to the nature of the X-server right? Running at a resolution of 768x1024 the vnc backend will simply forward the x-servers resolution to the clients, irregardless of whatever resolution the game is running. So would that not mean that the only games which does *not* require cropping are games running at fullscreen in the native 768x1024 resolution? 
Alternately environments not running through VNC, talking directly to the native x-server...

Anyway, I will not push this issue further, if its something you want I can add it, otherwise I will close this issue..

**Comment by gdb** [comment]
@jderehag Cropping is definitely useful, but I'm also a bit concerned about committing to maintaining wrappers which aren't definitely general-purpose. I think it might be useful to import them in a `wrappers.unstable` or `wrappers.experimental` key or something.

**Comment by jderehag** [comment]
@gdb Fair enough.
Are there some additional thoughts on doing the same for (for ex.) SafeActionSpace, which seems very experimental as well? Atleast in the long run..
Mainly asking in terms of if I should try and make something more general and consistant for wrappers like this or simply do a local solution for the cropping wrapper..

**Comment by gdb** [comment]
Great point. Want to move SafeActionSpace there, and any others that seem kinda questionable?

**Comment by jderehag** [comment]
Alright, will see what I can come up with..
Do I need to maintain backwards compatability (i.e for SafeActionSpace), or is it ok to break that?
You would need to change the imports for SafeActionSpace to wrapper.experimental.spaces (or somesuch).

**Comment by gdb** [comment]
Awesome. I'm ok breaking that one, but let's leave behind something that exceptions nicely.

**Comment by jderehag** [comment]
@gdb Great, perhaps you can assign this issue to me then? I dont have the access rights to do it myself..
