### ISSUE TITLE
Discussion for API unification

### ISSUE THREAD

**Issue by jderehag** [openai/universe#60]
Currently, the different environments have slightly different API:s, and depending on the environment you may apply one or more wrappers that modifies the environment (for instance, wrapper.Vision, wrapper.Vectorized).
The drawback right now is that you cannot daisy-chain wrappers for a specific environment unless the wrapped properties are different for each wrapper (which somewhat assumes that the user fairly intimitly knows the implementation of each wrapper).

This issue is submitted as an attempt to have a discussion on the future intention for universe API, and would more be used as a letter of intent on the overall direction of the API rather than producing a complete pull request changing the entire API to adhere to whatever would be the outcome of this discussion.

The way I see it is that the wrappers are really trying to solve 2 different problems.
1. Compensate for the fact that the API is inconsistant (see wrapper.(Un)Vectorized)
2. Standardize operations that most agents likely will want to do (Vision, SafeActionSpace)

### Issue 1 (API unification):
I would really like to see the API standardized instead of having every agent wrap the environment just to be able to run whatever gym they like.
Specfically, what I can think of now:
  1.1 Make every every environment vectorized
  1.2 Expand the action_space interface to to also include a list of actions (where len(actions) would be the maximum number of possible actions).

### issue 2 (daisy-chaining capability): 
I think its worth discussing how we really want to configure the environments (because, really, these are configurations in my opinion).
So the possibility to configure this should be possible on any environment (but would be a no-op where it makes sense).

Currently I can think of 2 approaches:
   2.1 Should we move things like action_space type instantiation to env.configure(action_space='discrete')
   2.2 Should we implement some daisy-chaining capability to the env wrappers?
         ex1: DiscreteActionSpace(SafeActionSpace(env))
         ex2: env.discrete_action_space().safe_action_space()

The daisy-chaining approach would be very powerful for lets say frame handling, where you could do:
env.crop_observations().resize(hight=42, width=42).grayscale()

But I would admit in this case that we would be bordering on what is best handled by numpy/opencv itself (and the users). But some very common operations could perhaps be maintained by universe (especially the ones that are depending on the environment).

**Comment by tlbtlbtlb** [comment]
> 1.2 Expand the action_space interface to to also include a list of actions (where len(actions) would be the maximum number of possible actions).

For discrete action spaces, `action_space.n` gives what you're asking for.

For continuous action spaces, a list isn't even theoretically possible.

For most universe environments the action space includes mouse events that can be at any screen position. A list of 1024x768 discrete actions doesn't seem useful.

> 2.2 Should we implement some daisy-chaining capability to the env wrappers?
ex1: DiscreteActionSpace(SafeActionSpace(env))

I'm not sure what you mean. Wrappers are usually nested several deep. For example, the stack created in https://github.com/openai/universe-starter-agent/blob/master/envs.py#L29-L45.

**Comment by jderehag** [comment]
> For discrete action spaces, action_space.n gives what you're asking for.
> 
> For continuous action spaces, a list isn't even theoretically possible.
> 
> For most universe environments the action space includes mouse events that can be at any screen position. A list of 1024x768 discrete actions doesn't seem useful.

The action_spaces I have managed to find (there may be more?):
Discrete (max_actions=.n, No way to index actions, only sample()) 
Hardcoded (max_actions=len(actions), index=action[index])
VNCActionSpace (max_actions=len(keys), index=keys (+pointerevents)
SafeActionSpace (Not really a action_space but more a proxy which sometimes overrides to a HardCoded action_space, so depending on the underlying action_space it could be all of the above)).

Any environment could potentially be seen as a discrete action_space (depending on the game, as you mention, for instance continous & mouse action based games). And I guess that is really the intention behind SafeActionSpace, to be able to cast any action_space to something more managable.

So once again, the main purpose here would be to *unify* the api:s where applicable. And personally I like the HardCoded one best where you simply have a list of potential actions.

>> 2.2 Should we implement some daisy-chaining capability to the env wrappers?
>> ex1: DiscreteActionSpace(SafeActionSpace(env))

> I'm not sure what you mean. Wrappers are usually nested several deep. For example, the stack created in https://github.com/openai/universe-starter-agent/blob/master/envs.py#L29-L45.

Lets say we would have 2 overlapping wrappers, one for cropping the agent frame, another for resizing to 42x42. If we would do them both as wrappers, and both are overriding def _observation(..), then only the last wrapper would be applied to that instance?
Or am I missing something here?

**Comment by tlbtlbtlb** [comment]
> Discrete (max_actions=.n, No way to index actions, only sample())

You can call `list(range(env.action_space.n))` to get what you want.

The wrappers wrap, not override methods. Each one's step function calls the step function of the wrapper it contains, and further modifies the result. (The `Env` class has a `step` method which calls `self._step` which, in a Wrapper, calls `self.env.step` on the env it's wrapping). So when you have a stack created like:
```
   env = FlashRescale(CropScreen(env, height, width, 84, 18))
```
the observation is first cropped, then rescaled.

**Comment by jderehag** [comment]
>You can call list(range(env.action_space.n)) to get what you want.
My main point was about having a consistant API.
So sure, alot of the issues I listed can be "fixed" on the agent side but I still think some of these things would benefit many users if they where fixed on the universe side.
 
>The wrappers wrap, not override methods. Each one's step function calls the step function of the wrapper it contains, and further modifies the result. (The Env class has a step method which calls self._step which, in a Wrapper, calls self.env.step on the env it's wrapping).
Ahh, that explains it! Thanks for the lesson.. =)
So that closes subissue number 2 (which to me was the biggest uncertainty regarding future patches).

If you like, I could close this issue and instead change the action_space API somewhat to simplify things on the agent side. Its probably easier to discuss things in the patch than here?
Or do you completely disagree with my ambition for a more unified API?
