### ISSUE TITLE
Ubuntu 16.04, gym.scoreboard.scoring.RewardPerTime() error

### ISSUE THREAD

**Issue by erilyth** [openai/universe#64]
When we install universe it installs gym via pip. This version of gym is outdated I presume, so it needs to be fixed. In the scoreboard's scoring.py file there is no RewardPerTime() in that version. Cloning the latest gym from github and using it there however fixes the issue. Could the pip version of gym be updated or is there something else that I am missing here?

**Comment by encore2020** [comment]
I meet with the same error to you

**Comment by erilyth** [comment]
@encore2020 A fix right now would be to find out the directory where gym has been installed by pip. In python doing `print gym.__file__` would give you the location. (Mine was /usr/local/lib/python2.7/dist-packages/gym/__init__.pyc). Now you just need to go there and clone the latest version of gym from https://github.com/openai/gym/tree/master/gym and replace all the contents in that folder.

**Comment by gdb** [comment]
Let me know if the above doesn't actually fix the issue.
