### ISSUE TITLE
"First Agent" Failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by zhengwx11** [openai/universe#74]
I'm connected to my host via VNC (port 5905)  for a GUI.
'First Agent' failed and I follow the suggest, run container by hand: 
`$ docker run -p 5900:5900 -p 15900:15900 --cap-add SYS_ADMIN --ipc host --privileged quay.io/openai/universe.flashgames:0.20.4` 
It also failed with :
```
Setting VNC and rewarder password: openai
[Thu Dec 22 00:54:46 UTC 2016] Waiting for /tmp/.X11-unix/X0 to be created (try 1/10)
[Thu Dec 22 00:54:46 UTC 2016] [/usr/local/bin/sudoable-env-setup] Disabling outbound network traffic for none
Traceback (most recent call last):
    File "/app/universe-envs/flashgames/init", line 262, in <module>
    sys.exit(main())
    File "/app/universe-envs/flashgames/init", line 243, in main
    setup_logdir(recorder_logdir)
    File "/app/universe-envs/flashgames/init", line 119, in setup_logdir
    os.makedirs(path, exist_ok=True)
    File "/usr/lib/python3.5/os.py", line 226, in makedirs
    head, tail = path.split(name)
    File "/usr/lib/python3.5/posixpath.py", line 103, in split
    i = p.rfind(sep) + 1
    AttributeError: 'NoneType' object has no attribute 'rfind'
```

It seems something is wrong inside the docker container. How should I fix it?

**Comment by tlbtlbtlb** [comment]
It's fixed in the latest release of the container. Update the version number in the docker run command to  `quay.io/openai/universe.flashgames:0.20.15`

**Comment by zhengwx11** [comment]
the docker is up and vnc connection is ok. I'll try the 'First Agent' again.
