### ISSUE TITLE
about gym installation

### ISSUE THREAD

**Issue by encore2020** [openai/universe#83]
Hi, I have reinstalled operation software of Ubuntu 16.

After doing all download, I found that there is no gym folder in the desk.
When I use import gym , the error of no gym will appear.

How is gym folder downloaded? How can I solve the problem?

**Comment by encore2020** [comment]
ubuntu@ubuntu-All-Series:~/universe$ sudo pip install -e .
[sudo] password for ubuntu: 
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///home/ubuntu/universe
Requirement already satisfied: autobahn in /usr/local/lib/python2.7/dist-packages (from universe==0.21.0)
Requirement already satisfied: docker-py==1.10.3 in /usr/local/lib/python2.7/dist-packages (from universe==0.21.0)
Requirement already satisfied: docker-pycreds==0.2.1 in /usr/local/lib/python2.7/dist-packages (from universe==0.21.0)
Requirement already satisfied: fastzbarlight>=0.0.13 in /usr/local/lib/python2.7/dist-packages (from universe==0.21.0)
Requirement already satisfied: go-vncdriver>=0.4.8 in /home/ubuntu/go-vncdriver (from universe==0.21.0)
Collecting gym>=0.6.0 (from universe==0.21.0)
Requirement already satisfied: Pillow in /usr/local/lib/python2.7/dist-packages (from universe==0.21.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python2.7/dist-packages (from universe==0.21.0)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from universe==0.21.0)
Requirement already satisfied: twisted in /usr/local/lib/python2.7/dist-packages (from universe==0.21.0)
Requirement already satisfied: ujson in /usr/local/lib/python2.7/dist-packages (from universe==0.21.0)
Requirement already satisfied: txaio>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from autobahn->universe==0.21.0)
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from docker-py==1.10.3->universe==0.21.0)
Requirement already satisfied: requests<2.11,>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from docker-py==1.10.3->universe==0.21.0)
Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python2.7/dist-packages (from docker-py==1.10.3->universe==0.21.0)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from docker-py==1.10.3->universe==0.21.0)
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from go-vncdriver>=0.4.8->universe==0.21.0)
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python2.7/dist-packages (from gym>=0.6.0->universe==0.21.0)
Requirement already satisfied: constantly>=15.1 in /usr/local/lib/python2.7/dist-packages (from twisted->universe==0.21.0)
Requirement already satisfied: incremental>=16.10.1 in /usr/local/lib/python2.7/dist-packages (from twisted->universe==0.21.0)
Requirement already satisfied: zope.interface>=3.6.0 in /usr/local/lib/python2.7/dist-packages (from twisted->universe==0.21.0)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from zope.interface>=3.6.0->twisted->universe==0.21.0)
Installing collected packages: gym, universe
  Found existing installation: universe 0.21.0
    Can't uninstall 'universe'. No files were found to uninstall.
  Running setup.py develop for universe
Successfully installed gym-0.6.0 universe

**Comment by tlbtlbtlb** [comment]
You appear to have installed both universe and gym. They are python modules, not desktop apps, so they won't appear on the desktop.
If you're still getting an error message running python code with `import gym`, can you report it here?

**Comment by encore2020** [comment]
When i import gym in python3, there is error
When I import gym in python (2.8), there is no error

**Comment by encore2020** [comment]
Another problem,  I could always run docker hello world rightly,

But in this command:
ubuntu@ubuntu-All-Series:~$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

This error will happen.

**Comment by encore2020** [comment]
ubuntu@ubuntu-All-Series:~$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
ubuntu@ubuntu-All-Series:~$ sudo service docker start
[sudo] password for ubuntu: 
ubuntu@ubuntu-All-Series:~$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
ubuntu@ubuntu-All-Series:~$ sudo docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

**Comment by encore2020** [comment]
ubuntu@ubuntu-All-Series:~$ python al.py
[2016-12-26 04:42:43,686] Making new env: flashgames.DuskDrive-v0
[2016-12-26 04:42:43,705] Writing logs to file: /tmp/universe-9010.log
Traceback (most recent call last):
  File "al.py", line 5, in <module>
    env.configure(remotes=1)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 226, in configure
    self._configure(*args, **kwargs)
  File "/home/ubuntu/universe/universe/vectorized/core.py", line 39, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 349, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 226, in configure
    self._configure(*args, **kwargs)
  File "/home/ubuntu/universe/universe/wrappers/render.py", line 18, in _configure
    super(Render, self)._configure(**kwargs)
  File "/home/ubuntu/universe/universe/vectorized/core.py", line 39, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 349, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 226, in configure
    self._configure(*args, **kwargs)
  File "/home/ubuntu/universe/universe/wrappers/throttle.py", line 27, in _configure
    super(Throttle, self)._configure(**kwargs)
  File "/home/ubuntu/universe/universe/vectorized/core.py", line 39, in _configure
    super(Wrapper, self)._configure(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 349, in _configure
    return self.env.configure(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 226, in configure
    self._configure(*args, **kwargs)
  File "/home/ubuntu/universe/universe/envs/vnc_env.py", line 193, in _configure
    use_recorder_ports=record,
  File "/home/ubuntu/universe/universe/remotes/build.py", line 19, in build
    n=n,
  File "/home/ubuntu/universe/universe/remotes/docker_remote.py", line 43, in __init__
    self._assigner = PortAssigner(reuse=reuse)
  File "/home/ubuntu/universe/universe/remotes/docker_remote.py", line 149, in __init__
    self.client, self.info = get_client()
  File "/home/ubuntu/universe/universe/remotes/docker_remote.py", line 143, in get_client
    return docker.Client(base_url=host, version=client_api_version), info
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 99, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 124, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))
ubuntu@ubuntu-All-Series:~$

**Comment by encore2020** [comment]
I could run docker ps rightly now , the meet with the above error

**Comment by tlbtlbtlb** [comment]
You need to configure docker so you can use it without sudo. See https://docs.docker.com/engine/installation/linux/ubuntulinux/#manage-docker-as-a-non-root-user

**Comment by encore2020** [comment]
I have done that, but I still see docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.

ubuntu@ubuntu-All-Series:~$ sudo groupadd docker
[sudo] password for ubuntu: 
groupadd: group 'docker' already exists
ubuntu@ubuntu-All-Series:~$ sudo usermod -aG docker ubuntu
ubuntu@ubuntu-All-Series:~$ docker run hello-world
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
ubuntu@ubuntu-All-Series:~$ env | grep DOCKER_HOST
ubuntu@ubuntu-All-Series:~$ sync
ubuntu@ubuntu-All-Series:~$ docker run hello-world
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
ubuntu@ubuntu-All-Series:~$

**Comment by encore2020** [comment]
I could only run sudo docker run hello-world

ubuntu@ubuntu-All-Series:~$ sudo docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

**Comment by encore2020** [comment]
The question is resolved, I could open the game now.
Thank you for you help.
