### ISSUE TITLE
How to train my own data on the platform

### ISSUE THREAD

**Issue by encore2020** [openai/universe#84]
Hello, thank you for you help.  I could open the game now, but I found the AI computer does not play the game well,  always go out of the road and hit some cars in front of itself.

So I have two questions now.
1)  Next step, how could I train the computer by myself to improve the AI computer skill , could you provide some link of that to me?
2)  I have a friend that he is also installing the platform, but he could not download the game successfully, the process always be broken because of timeout.  Could you provide the address that could be download by HTTP directly?

**Comment by tlbtlbtlb** [comment]
1. is an open research problem. An overview of various approaches is at https://people.eecs.berkeley.edu/~pabbeel/cs287-fa12/slides/inverseRL.pdf

2. It's not clear what is timing out. Have him submit an issue with a complete log showing what may have failed.
