### ISSUE TITLE
Chrome set up issue in AWS

### ISSUE THREAD

**Issue by rajeev921** [openai/universe#88]
Hi I have done all the proper set up in AWS.  But when I started running it  by the below command but not getting anything on terminal.

universe) $ cd ~
(universe) $ git clone https://github.com/openai/universe-starter-agent.git
(universe) $ cd ~/universe-starter-agent
(universe) $ python train.py --num-workers 2 --env-id gym-core.PongDeterministic-v3 --log-dir /tmp/vncpong

$ tmux a

Can anyone help me on this.

**Comment by tlbtlbtlb** [comment]
Need more detail. What do you see after running `tmux a`? What does `docker ps` show?

**Comment by rajeev921** [comment]
Attached the o/p that I am seeing after running tmux a
![aws](https://cloud.githubusercontent.com/assets/8274880/21600977/43e84b4c-d1aa-11e6-8d38-1b4eb552cbee.JPG)

I have gone through the blog but nowhere it is mentioned about the setup in AWS.

I have done the setup in AWS without any hussle.
But if you could provide more information about how to start and run it there. 
It will be very helpful. Any links comments are welcome.

Thanks,
Rajeev

**Comment by tlbtlbtlb** [comment]
Looks like it's working. Tmux lets you switch between the different views, and starts with htop. Type ^B <number> to switch views, listed at the bottom. ^B 1 will show you one of the worker outputs (w-0). More tmux commands at http://manpages.ubuntu.com/manpages/precise/en/man1/tmux.1.html

**Comment by rajeev921** [comment]
Ok understood that part, Still have these 2 question.

1. > I am not able to see any video. Can you tell me When I run this file  What are the additional step I have to do to see the video?

2.> To connect to the vnc I have used  http://localhost:6006/.
Here in the place of local host, I am giving the IP address of AWS currently running instance Public IP. 
And added port 6006 also in the security. 
But still not able to connect to vnc.

**Comment by tlbtlbtlb** [comment]
It's tricky to make Docker containers listen on external ports. It's easier to use ssh to forward the ports. From your local machine, run
```
$ ssh -L 6006:localhost:6006 -L 12345:localhost:12345 <aws instance>
```
and leave that ssh connection open. Then tell your VNC client connect to localhost:6006. TurboVNC works best. And to see the Tensorboard, point your browser to localhost:12345.

I'm surprised if you got port 6006 using universe-starter-agent: ports 5900 .. 5920 are more likely. You can check by running `docker ps` on the AWS machine -- it should show port assignments.
