### ISSUE TITLE
import go_vncdriver error ...

### ISSUE THREAD

**Issue by billyon** [openai/universe#89]
i run the example code and i get this error:
Traceback (most recent call last):
  File "code.py", line 2, in <module>
    import universe  # register the universe environments
  File "/home/billykon/desktop/python bot/universe/universe/__init__.py", line 22, in <module>
    from universe import error, envs
  File "/home/billykon/desktop/python bot/universe/universe/envs/__init__.py", line 1, in <module>
    import universe.envs.vnc_env
  File "/home/billykon/desktop/python bot/universe/universe/envs/vnc_env.py", line 18, in <module>
    import go_vncdriver
ImportError: dynamic module does not define module export function (PyInit_go_vncdriver)

**Comment by tlbtlbtlb** [comment]
That indicates some build or install problem with go_vncdriver. What OS and Python version are you using? How did you install it? What does `pydoc go_vncdriver` report?

**Comment by tlbtlbtlb** [comment]
It doesn't seem like it's installed at all. Did you do the final `pip install -e ./` step? Can you provide a transcript of how you built and installed it?

**Comment by billyon** [comment]
yes i did tha last.
1)git clone https://github.com/openai/go-vncdriver.git
2)cd go-vncdriver
3)./build.py
4)pip3 install -e ./

**Comment by billyon** [comment]
ok here it is:
`billykon@billykon-K5130:~/Επιφάνεια εργασίας/python bot/go-vncdriver$ sudo ./build.sh 
[sudo] password for billykon: 
Env info:

export GOPATH='/home/billykon/Επιφάνεια εργασίας/python bot/go-vncdriver/.build'
export CGO_CFLAGS='-I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7'
export CGO_LDFLAGS='/usr/lib/x86_64-linux-gnu/libjpeg.so -L/usr/lib -lpython2.7'
export GO15VENDOREXPERIMENT='1'

Running build with OpenGL rendering.
Building with OpenGL: GOPATH=/home/billykon/Επιφάνεια εργασίας/python bot/go-vncdriver/.build go build -buildmode=c-shared -o go_vncdriver.so github.com/openai/go-vncdriver. (Set GO_VNCDRIVER_NOGL to build without OpenGL.)
billykon@billykon-K5130:~/Επιφάνεια εργασίας/python bot/go-vncdriver$ sudo pip3 install -e .
The directory '/home/billykon/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/billykon/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///home/billykon/%CE%95%CF%80%CE%B9%CF%86%CE%AC%CE%BD%CE%B5%CE%B9%CE%B1%20%CE%B5%CF%81%CE%B3%CE%B1%CF%83%CE%AF%CE%B1%CF%82/python%20bot/go-vncdriver
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from go-vncdriver==0.4.19)
Installing collected packages: go-vncdriver
  Found existing installation: go-vncdriver 0.4.19
    Can't uninstall 'go-vncdriver'. No files were found to uninstall.
  Running setup.py develop for go-vncdriver
Successfully installed go-vncdriver
`

**Comment by billyon** [comment]
oh wait i tried instead of ./build.py to run : python3 build.py and after that i did pip3 install -e . and it looks like its running now.
Thanks for trying to help and have a good new year :)
