### ISSUE TITLE
Faster and more stable Docker image mirror sites

### ISSUE THREAD

**Issue by futurely** [openai/universe#90]
It is extremely slow and unstable to download the Docker images from quay.io at least in China even without being behind a firewall or using a proxy. Running `env.configure(remotes=1)` always ends up with errors immediately or after waiting for dozens of minutes. Would you please set up a Docker registry mirror in China?

docker.errors.APIError: 500 Server Error: Internal Server Error ("{"message":"Get https://quay.io/v2/openai/universe.world-of-bits/manifests/0.20.0: net/http: TLS handshake timeout"}")

universe.remotes.compose.progress_stream.StreamOutputError: read tcp 192.168.1.6:34020->54.231.72.91:443: read: connection reset by peer

universe.remotes.compose.progress_stream.StreamOutputError: net/http: TLS handshake timeout

docker.errors.APIError: 500 Server Error: Internal Server Error ("{"message":"Get https://quay.io/v1/_ping: net/http: TLS handshake timeout"}")

**Comment by tlbtlbtlb** [comment]
I think that's a different problem than the China-US connection. The file it's getting an error on (https://quay.io/v2/openai/universe.world-of-bits/manifests/0.20.0) is only 35 kB. I think you are being blocked by a firewall.

**Comment by futurely** [comment]
Probably due to the G*W. No VPN available to bypass it.

**Comment by futurely** [comment]
An alternative choice is to host on hub.docker.com which has several free mirrors.

DaoCloud Announces Docker Hub Mirror service is permanently free

http://blog.daocloud.io/daocloud-mirror-free/

https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fblog.daocloud.io%2Fdaocloud-mirror-free%2F&edit-text=

https://c.163.com/hub#/m/home/

https://dev.aliyun.com/search.html

**Comment by tlbtlbtlb** [comment]
We can also push to docker hub. The current versions are there, so
```
docker pull openai/universe.world-of-bits:0.20.0
```
works. I tried 
```
docker pull m.daocloud.io/openai/universe.world-of-bits:0.20.0
```
but that didn't work. Do we have to register the repository with daocloud, or does it work for you by setting registry-mirror?

**Comment by futurely** [comment]
Thanks a lot! It works. DaoCloud needs to be signed in to get a personal mirror ID.

https://www.daocloud.io/mirror#accelerator-doc

curl -sSL https://get.daocloud.io/daotools/set_mirror.sh | sh -s http://MIRRORID.m.daocloud.io

```
docker pull openai/universe.flashgames:latest
docker pull openai/universe.gym-core:0.20.0
docker pull openai/universe.world-of-bits:0.20.0
```
Since the automatic local remotes still tries to download from quay.io, manual remotes has to be created which is cumbersome. `export OPENAI_DOCKER_REPO=docker.io/openai` solved the problem. The flashgames runtime's latest version "0.20.15" has to be replaced with "latest" in [runtimes.yml](https://github.com/openai/universe/blob/3023c608c266d0773610e2964a8dcab74708139d/universe/runtimes.yml) to use the mirror. The document should also be improved.

**Comment by tlbtlbtlb** [comment]
@futurely Thanks! We'll make it work seamlessly and document this for other people in China.

**Comment by tlbtlbtlb** [comment]
I added a note on this to the wiki: https://github.com/openai/universe/wiki/Solutions-to-common-problems#docker-wont-pull-images

**Comment by Fredilly** [comment]
curl -sSL https://get.daocloud.io/daotools/set_mirror.sh | sh -s http://MIRRORID.m.daocloud.io
I get "OS not supported error". This seems to be the command line for linux. How do I get it to work on Mac?

**Comment by futurely** [comment]
daocloud.io did not update the mirrors very timely. Try the official site quay.io first.

**Comment by GoingMyWay** [comment]
@Fredilly , add  `http://MIRRORID.m.daocloud.io` to Registry mirrors of Mac Docker[Daemon preference], you should get a MIRRORID in daocloud.io. But as @futurely said, daocloud.io doesn't update the mirror timely, so for users from China, the best way to pull the image is to pull the image on a VPN and send the image to your host.

**Comment by tarvos21** [comment]
@Fredilly If you want to use DaoCloud, then I guess you are in China, I have written a small article about how to download Docker images through proxies you already set up, maybe it can be helpful: https://zhuanlan.zhihu.com/p/26033249
