### ISSUE TITLE
Question about vnc client browser and flash games

### ISSUE THREAD

**Issue by CharlesJQuarra** [openai/universe#92]
Hi,

When I run the sample code:

```
env = gym.make('flashgames.DuskDrive-v0')
env.configure(remotes=1)  # automatically creates a local docker container
observation_n = env.reset()
print observation_n

while True:
  action_n = [[('KeyEvent', 'ArrowUp', True)] for ob in observation_n]  # your agent here
  observation_n, reward_n, done_n, info = env.step(action_n)
  print observation_n
  print reward_n
  print info
  env.render()
```

I get a window with a browser that looks like chrome or firefox where the flashgames are running. 

I was expecting it to be running inside the docker instance, and was also expecting perhaps the browser command to be specified inside the `ENTRYPOINT` directive inside the `Dockerfile`, but examining the `Dockerfile` I don't see anything specifying what command is run inside the docker instance, other than the go vnc client inside `universe/envs/vnc_env.py`

Where is the browser command being specified?

**Comment by catherio** [comment]
Hi @CharlesJQuarra,

Indeed, the window is a Chrome browser running inside a Docker instance on your local machine.

Just to be clear, what Dockerfile are you looking at? The `universe` repository does not include the code that runs inside the Docker container - we plan to tidy up the code that's inside the Docker for a fully supported public release within the next few months.

The command that gets run inside Docker does more than just start a browser - it configures a more substantial environment-side control plane that we wrote, which handles the rewarder channel connection to the agent, revives the browser if it crashes (you can try doing `open vnc://localhost:5900` after running that command, and then manually clicking "close" on the browser tab... within a few seconds the browser comes back!), and more. 

If you let us know what it is you'd like to do with the browser command inside the Docker container, we can help you figure out how to do what it is you'd like to do!

**Comment by catherio** [comment]
I'm going to close this github issue, as there is no bug report here for us to fix, but if you have followup questions please don't hesitate to ask us on https://discuss.openai.com/. Good luck with Universe!
