### ISSUE TITLE
dynamic module does not define module export function (PyInit_go_vncdriver)

### ISSUE THREAD

**Issue by CIcarus** [openai/universe#93]
running:

import universe

results in:

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-917a504b1f6f> in <module>()
----> 1 import universe

/universe/universe/__init__.py in <module>()
     20 import universe.scoreboard
     21 import universe.configuration
---> 22 from universe import error, envs
     23 from universe.remotes import docker_remote
     24 from universe.rewarder import merge_infos

/universe/universe/envs/__init__.py in <module>()
----> 1 import universe.envs.vnc_env
      2 from universe.envs.vnc_env import VNCEnv
      3 from universe.envs.vnc_core_env import GymCoreEnv, GymCoreSyncEnv
      4 from universe.envs.vnc_flashgames import FlashgamesEnv
      5 from universe.envs.vnc_internet import InternetEnv

/universe/universe/envs/vnc_env.py in <module>()
     16 # driver here.
     17 # noinspection PyUnresolvedReferences
---> 18 import go_vncdriver
     19 
     20 logger = logging.getLogger(__name__)

ImportError: dynamic module does not define module export function (PyInit_go_vncdriver)
`
This only occurs after following instructions at [https://github.com/openai/go-vncdriver](https://github.com/openai/go-vncdriver) in order to resolve the OpenGL dependency issue. Normal install of universe runs. (but doesn't show dusk drive being played.)

Would you be able to point me in the right direction?

On ubuntu 16.04

**Comment by tlbtlbtlb** [comment]
Most likely, you compiled go-vncdriver with a different version of python than you're using to run.

In the go-vncdriver directory run
```
$ python build.py
$ pip install -e ./
```
If you use a different python (like python3 & pip3) replace with those.

**Comment by CIcarus** [comment]
Using:

`python3 build.py`

fixed the issue.

Thank you / Kind regards.
